ON=1; OFF=0;
pathname = 'X:\Preycapture';%miyazaki path 
n=0;


%%%group: 1=100; 2=50 ; 3=25; 4=12.5; 5=6.25;6=3.1, 7=0
%%%female=1 and male=2;
%%%contrast:100,50, 25, 12.5, and 6.25, percent transmittance
%%%size:100, 50, 25, 12.5, 6.25, scaled down size along all dimensions of
%%%ellipse (naturalistic stimuli)

n=n+1;
files(n).subj = 'prey18_LT_FS_LS_trial1';
files(n).lighting = ON;
files(n).trackpts = 'Plexiglass_7_26_16\Prey18_LT_FS_LS_trial1\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=2;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=120;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey18_LT_FS_LS_trial1.avi';
files(n).body=0;
% 
n=n+1;
files(n).subj = 'Prey18_LT_FS_LS_trial3';
files(n).lighting = ON;
files(n).trackpts = 'Plexiglass_7_26_16\Prey18_LT_FS_LS_trial3\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=2;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey18_LT_FS_LS_trial3.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey18_LT_FS_RS_trial5';
files(n).lighting = ON;
files(n).trackpts = 'Plexiglass_7_26_16\Prey18_LT_FS_RS_trial5\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=2;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey18_LT_FS_RS_trial5.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey18_LT_NIR_LS_trial6';
files(n).lighting = OFF;
files(n).trackpts = 'Plexiglass_7_26_16\Prey18_LT_NIR_LS_trial6\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=2;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey18_LT_NIR_LS_trial6.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey18_LT_NIR_RS_trial2';
files(n).lighting = OFF;
files(n).trackpts = 'Plexiglass_7_26_16\Prey18_LT_NIR_RS_trial2\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=2;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey18_LT_NIR_RS_trial2.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey18_LT_NIR_RS_trial4';
files(n).lighting = OFF;
files(n).trackpts = 'Plexiglass_7_26_16\Prey18_LT_NIR_RS_trial4\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=2;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey18_LT_NIR_RS_trial4.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey19_LT_FS_LS_Trial4';
files(n).lighting = ON;
files(n).trackpts = 'Plexiglass_7_26_16\Prey19_LT_FS_LS_Trial4\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey19_LT_FS_LS_Trial4.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey19_LT_FS_LS_Trial4';
files(n).lighting = ON;
files(n).trackpts = 'Plexiglass_7_26_16\Prey19_LT_FS_LS_Trial4\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey19_LT_FS_LS_Trial4.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey19_LT_FS_RS_Trial2';
files(n).lighting = ON;
files(n).trackpts = 'Plexiglass_7_26_16\Prey19_LT_FS_RS_Trial2\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey19_LT_FS_RS_Trial2.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey19_LT_FS_RS_Trial6';
files(n).lighting = ON;
files(n).trackpts = 'Plexiglass_7_26_16\Prey19_LT_FS_RS_Trial6\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey19_LT_FS_RS_Trial6.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey19_LT_NIR_LS_Trial1';
files(n).lighting = OFF;
files(n).trackpts = 'Plexiglass_7_26_16\Prey19_LT_NIR_LS_Trial1\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey19_LT_NIR_LS_Trial1.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey19_LT_NIR_LS_Trial3';
files(n).lighting = OFF;
files(n).trackpts = 'Plexiglass_7_26_16\Prey19_LT_NIR_LS_trial3\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey19_LT_NIR_LS_trial3.avi';
files(n).body=0;
%
n=n+1;
files(n).subj = 'Prey19_LT_NIR_RS_Trial5';
files(n).lighting = OFF;
files(n).trackpts = 'Plexiglass_7_26_16\Prey19_LT_NIR_RS_Trial5\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100; %enter grey filter ID
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=1; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Plexiglass_7_26_16\Prey19_LT_NIR_RS_Trial5.avi';
files(n).body=0;
%%

n=n+1;
files(n).subj = 'Prey18_LT_slide 50';
files(n).lighting = ON;
files(n).trackpts = 'Contrast_virtualstim_8_12_16\Prey18\Prey18_LT_contrast_slide50\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 6.25; % % decrease
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=5; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime='';
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey18_LT_slide 51';
files(n).lighting = ON;
files(n).trackpts = 'Contrast_virtualstim_8_12_16\Prey18\Prey18_LT_contrast_slide51\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50; % % decrease
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=2; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime='';
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey18_LT_slide 52';
files(n).lighting = ON;
files(n).trackpts = 'Contrast_virtualstim_8_12_16\Prey18\Prey18_LT_contrast_slide52\Tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 3; % % decrease
files(n).size = 100; % enter scaled virtual stimuli ID
files(n).notes = '';
files(n).fps=60; 
files(n).scale=28;%pixels/cm on video tracking
files(n).group=6; %assign difference grey or size values to group numbers 
files(n).sex=1;
files(n).FrameS=1; %frame where cricket is first available
files(n).FrameEnd=1000; %frame where cricket is caught
files(n).CapTime='';
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=0;



