function layer_bar_inh_median(data,used,exc,inh,layertwo,layerthree,layerfour,layerfive,layersix)
figure
barweb_median([median(data(used&exc&layertwo)), median(data(used&exc&layerthree)), median(data(used&exc&layerfour)) ,median(data(used&exc&layerfive)),median(data(used&exc&layersix)),median(data(used&inh)); 0 0 0 0 0 0]', ...
    [med_se(data(used&exc&layertwo),5)+ sqrt(-1)* med_se(data(used&exc&layertwo),95), ...
   med_se(data(used&exc&layerthree),5)+ sqrt(-1)* med_se(data(used&exc&layerthree),95), ...
   med_se(data(used&exc&layerfour),5)+ sqrt(-1)* med_se(data(used&exc&layerfour),95), ...
   med_se(data(used&exc&layerfive),5)+ sqrt(-1)* med_se(data(used&exc&layerfive),95), ...
   med_se(data(used&exc&layersix),5)+ sqrt(-1)* med_se(data(used&exc&layersix),95), ...
   med_se(data(used&inh),5)+ sqrt(-1)* med_se(data(used&inh),95), ...
      ; 0 0 0 0 0 0]',  2,{'upper 2/3' 'lower 2/3' '4' '5' '6' 'inh'},[],[],[],[0 0 .95]);
set(gca,'xticklabel', {'upper 2/3', 'lower 2/3', '4', '5' '6' 'inh'})
set(gca,'FontSize',14)

