clear; close all;
% Choose avi file 
[f,p] = uigetfile({'*.avi';},'choose Left eye EyeFilt');
% Read in Eye Tracking Video
if f ~=0
    TempVid = VideoReader(fullfile(p,f));
    frame=1; k=1;
    while hasFrame(TempVid) 
        EyeVidL(:,:,frame) = rgb2gray(readFrame(TempVid));
        if mod(frame,100)==0
            fprintf('frame = %d\n',frame)
        end
        frame=frame+1;
        
    end
    % Load the .csv file generated by DLC
    [f2,p2] = uigetfile({'*.csv';},'choose DLC Left Points File');
    Pointsxy = csvread(fullfile(p2,f2),1,0);
    vidsize=1:size(EyeVidL,3); %1:1000;
    PointsxL = Pointsxy(vidsize,[7:3:end]); PointsyL = Pointsxy(vidsize,[8:3:end]);
    LHL =  Pointsxy(vidsize,[9:3:end]);
   
    
end
fprintf('Done Reading in Left Video \n');


[f,p] = uigetfile({'*.avi';},'choose Right eye EyeFilt');
% Read in Eye Tracking Video
if f ~=0
    TempVidR = VideoReader(fullfile(p,f));
    frameR=1; k=1;
    while hasFrame(TempVidR) 
        EyeVid(:,:,frameR) = rgb2gray(readFrame(TempVidR));
        if mod(frameR,100)==0
            fprintf('frame = %d\n',frameR)
        end
        frameR=frameR+1;
        
    end
    % Load the .csv file generated by DLC
    [f2,p2] = uigetfile({'*.csv';},'choose DLC Points File R eye');
    Pointsxy = csvread(fullfile(p2,f2),1,0);
    vidsize=1:size(EyeVid,3); %1:1000;
    Pointsx = Pointsxy(vidsize,[7:3:end]); Pointsy = Pointsxy(vidsize,[8:3:end]);
    LH =  Pointsxy(vidsize,[9:3:end]);
   
    
end
fprintf('Done Reading in Right Video \n');



%%


% Read in Top Video

[f,p] = uigetfile({'*.avi';},'choose Top video');
% Read in Eye Tracking Video
if f ~=0
    TempVidT = VideoReader(fullfile(p,f));
    frame=1; k=1;
 
    while hasFrame(TempVidT)
        TopVid(:,:,frame) = imresize(rgb2gray(readFrame(TempVidT)),.25);
 if mod(frame,100)==0
            fprintf('frame = %d\n',frame)
        end
        frame=frame+1;
        
    end
end
fprintf('Done Reading in Top Video \n');

  % Load the .csv file generated by DLC
    [f2,p2] = uigetfile({'*.csv';},'choose DLC Points File Top');
   % PointsxyT = csvread(fullfile(p2,f2),1,0);
    PointsxyT = csvread(fullfile(p2,f2),3,1);

    vidsizeT=1:size(TopVid,3); %1:1000;
    PointsxT = PointsxyT(vidsizeT,[1:3:end]); PointsyT = PointsxyT(vidsizeT,[2:3:end]);
    LHT =  PointsxyT(vidsizeT,[3:3:end]);
   


j=1;
for i=1:size(LHT,1)
    if isempty(find(LHT(i,:)<.95))~=1 || any(PointsxT(i,:) <= 10 & PointsxT(i,:) <=10)
        bdfitT(j,1) = i; j=j+1;
    end
end


% %% Set Bad tracking to NaN and clean data;
% bdfit_all = setdiff(bdfitT,bdfit); %bdfit;% 
% PointsxT(bdfitT,:)=NaN; PointsyT(bdfitT,:)=NaN; 
% Pointsx(bdfit,:)=NaN; Pointsy(bdfit,:)=NaN; 
% save('J436b_cricket3_041019b.mat');

%% Plot Ellipse Fits on Image (L eye)
%figure;
axis tight manual
ax = gca;
ax.NextPlot = 'replaceChildren';
axis([1 size(EyeVidL,1) 1 size(EyeVidL,2)] )
% EllipseParams = zeros(size(EyeVid,3),6);

for v=1:size(EyeVidL,3)
  %  imagesc(EyeVid(:,:,v)); colormap gray; axis equal off; hold on;
    scatter(PointsxL(v,:),PointsyL(v,:),100,'.r'); % Uncomment if you wish plot points
    if ~any((PointsxL(v,:)<10 | PointsyL(v,:)<10)) % check points
        e_tL = fit_ellipse(PointsxL(v,:),PointsyL(v,:),ax);
         if isempty(e_tL.status)==1 &&  ((e_tL.short_axis/2)/(e_tL.long_axis/2) >.5)
            EllipseParamsL(v,:)=[e_tL.X0_in, e_tL.Y0_in, e_tL.long_axis/2, e_tL.short_axis/2,  e_tL.angleToX*pi/180, e_tL.angleFromX*pi/180, e_tL.phi];
            ExtraParamsL(v,:) = [e_tL.X0, e_tL.Y0, e_tL.a, e_tL.b, e_tL.cos_phi, e_tL.sin_phi];
        end
    end
   % hold off;
    title(sprintf('Left Eye Frame = %d',v));
   % drawnow limitrate

%     pause
end




%% Plot Ellipse Fits on Image (R eye)
%figure;
axis tight manual
ax = gca;
ax.NextPlot = 'replaceChildren';
axis([1 size(EyeVid,1) 1 size(EyeVid,2)] )
% EllipseParams = zeros(size(EyeVid,3),6);

for v=1:size(EyeVid,3)
  %  imagesc(EyeVid(:,:,v)); colormap gray; axis equal off; hold on;
    scatter(Pointsx(v,:),Pointsy(v,:),100,'.r'); % Uncomment if you wish plot points
    if ~any((Pointsx(v,:)<10 | Pointsy(v,:)<10)) % check points
        e_t = fit_ellipse(Pointsx(v,:),Pointsy(v,:),ax);
         if isempty(e_t.status)==1 &&  ((e_t.short_axis/2)/(e_t.long_axis/2) >.5)
            EllipseParams(v,:)=[e_t.X0_in, e_t.Y0_in, e_t.long_axis/2, e_t.short_axis/2,  e_t.angleToX*pi/180, e_t.angleFromX*pi/180, e_t.phi];
            ExtraParams(v,:) = [e_t.X0, e_t.Y0, e_t.a, e_t.b, e_t.cos_phi, e_t.sin_phi];
        end
    end
   % hold off;
    title(sprintf('Right Eye, Frame = %d',v));
   % drawnow limitrate

%     pause
end


%% Top vid + points

figure
axis tight manual
ax = gca;
ax.NextPlot = 'replaceChildren';
axis([1 size(TopVid,1) 1 size(TopVid,2)] )

u=PointsxT./4; b =PointsyT./4;
vidfile = VideoWriter('top_approachcapture_J436b_041219a.mp4','MPEG-4');
open(vidfile);
for v=1:600%size(TopVid,3)
    imagesc(TopVid(:,:,v)); colormap gray; axis equal off; hold on;
   %scatter(PointsxT(v,:),PointsyT(v,:),100,'.g'); % Uncomment if you wish plot points
    scatter(u(v,:),b(v,:),100,'.g'); % Uncomment if you wish plot points

    drawnow limitrate
    %title(sprintf('Top, Frame = %d',v));
        title(sprintf('Time(s) = %d',round(v/30)));
   F(v) = getframe(gcf); 
    writeVideo(vidfile,F(v));
    fprintf('Frame = %d \n',v);

end
close(vidfile)



%%
figure;
axis tight manual
ax = gca;
ax.NextPlot = 'replaceChildren';
vidfile = VideoWriter('full_approachcapture_041619a.mp4','MPEG-4');
open(vidfile);



clear xR yR xL yL
xR = medfilt1(EllipseParams(:,1),10); yR = medfilt1(EllipseParams(:,2),10);
xL = medfilt1(EllipseParamsL(:,1),10); yL = medfilt1(EllipseParamsL(:,2),10);


xR = xR-mean(xR); yR = yR-mean(yR);
xL = xL-mean(xL); yL = yL-mean(yL);


longL = EllipseParamsL(:,3); shortL = EllipseParamsL(:,4);
radL = longL+shortL./2*length(shortL)

long = EllipseParams(:,3); short = EllipseParams(:,4);
rad = long

%10410:10680


for v=10450:10500%10300:10850%5800:6800%size(EyeVid,3)
 
    
    subplot(4,3,3)
    imagesc(EyeVidL(:,:,v)); colormap gray; hold on; axis equal off;
    scatter(PointsxL(v,:),PointsyL(v,:),100,'.b'); hold off; % Uncomment if to plot DLC points too
%     if ~any((Pointsx(v,:)<10 | Pointsy(v,:)<10)) % check points
%         e_t = fit_ellipse(Pointsx(v,:),Pointsy(v,:),ax);
%     end

    subplot(4,3,6)
    imagesc(EyeVid(:,:,v)); colormap gray; hold on; axis equal off;
    scatter(Pointsx(v,:),Pointsy(v,:),100,'.r'); hold off; % Uncomment if to plot DLC points too
%     if ~any((Pointsx(v,:)<10 | Pointsy(v,:)<10)) % check points
%         e_t = fit_ellipse(Pointsx(v,:),Pointsy(v,:),ax);
%     end
    title(sprintf('Time(s) = %d',round(v/30)));
    drawnow limitrate;

    subplot(4,3, [9 12])
     plot(xR(v),yR(v),'r.'); axis square;%ylim([-60 60]); xlim([-100 100]);
     hold on
     plot(xL(v),yL(v),'b.')
     if v==10410%5940
         title('APPROACH')
     end

if v>=10680 %6450 
    title('CAPTURE')
end

    xlabel('x centroid'); ylabel ('y centroid');
 %   legend({'right eye', 'left eye'});
    drawnow limitrate;
    
    
    
     subplot(4,3,[7 8 10 11])
    plot(normalize(medfilt1(radL,10)),'b'); xlim([10000 11000]);
    hold on
    plot(normalize(medfilt1(rad,10)),'r'); 
    
    plot(v,.9,'g*','MarkerSize', 15); ylim([.35 1]);
%     plot([5940 5940],[0 1],'-k','Linewidth',4)    
%     plot([6450 6450],[0 1],'-k','Linewidth',4)    

   plot([10390 10390],[0 1],'-k','Linewidth',4)    
    plot([10720 10720],[0 1],'-k','Linewidth',4)  

    %set(gca,'xtick',([1:1800:size(EyeVid,3)]))% tick every 30 seconds
    %set(gca,'xtick',([5800:450:6800]))% tick every 30 seconds
    set(gca,'xtick',([10250:450:10800]))% tick every 30 seconds

    set(gca,'xticklabels',({'15','30','45'}),'FontSize',10)

    %set(gca,'xticklabels',({'1','2','3','4','5','6','7','8','9','10','11','12','13'}),'FontSize',10)
    
    
    xlabel('Time (s)'); ylabel ('normalized pupil radius');
 %   legend('left eye', 'right eye');
    drawnow limitrate;
    hold off
    
    
    subplot(4,3,[1 2 4 5])
    imagesc(TopVid(:,:,v)); colormap gray; axis equal off; hold on;
    scatter(PointsxT(v,:),PointsyT(v,:),100,'.g'); % Uncomment if you wish plot points
     drawnow limitrate
    
    F(v) = getframe(gcf); 
    writeVideo(vidfile,F(v));
    fprintf('Frame = %d \n',v);
end
close(vidfile)