ON=1; OFF=0;
%pathname = 'X:\';%miyazaki path to prey capture folder stored on Eyre
%pathname='E:\Prey_capture_data\'; %eyre path
pathname = 'Y:\' % is path on Niell V2

% if ismac
%     pathname = '/Users/crisniell/Dropbox/Prey capture/Prey_tracks/'
% end
% 
% pathname = '/Users/crisniell/Dropbox/Prey capture/Prey_tracks/'
% 

n=0;


%%%group: 1=wt blk6; 2= Dark 1st exp; 3=eyeSuture; 4=Bbgd; 5=earPlug;
% 6=EyeReopen; 7=EarUnplugged; 8=blind mice; 10=ctl Blind
%%%female=1 and male=2

n=n+1;
files(n).subj = 'prey7_LT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey7_LT_60\Prey7_LT_FS_trial1_60\tracks\DLTdv5_data_xypts.csv';%specific path and file name
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=407;%frame where cricket is first available
files(n).FrameEnd=1079;%frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey7_LT_60\Prey7_LT_FS_trial1_60.avi';
files(n).body=1;


n=n+1;
files(n).subj = 'prey7_LT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey7_LT_60\Prey7_LT_FS_trial2_60\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=450;%frame where cricket is first available
files(n).FrameEnd=930;%frame where cricket is caught
files(n).CapTime=8;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey7_LT_60\Pry7_LT_FS_trial2_60.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'prey7_RT';
files(n).lighting = ON;
files(n).trackpts = 'Dark_1st_time_3_15_16\Prey7_RT_dark_FS_trial1\tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=186;%frame where cricket is first available
files(n).FrameEnd=538;%frame where cricket is caught
files(n).CapTime=6;
files(n).FrameFlash='';
files(n).Moviefile='Dark_1st_time_3_15_16\Prey7_RT_dark_FS_trial1.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'prey7_TT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey7_TT_60\Prey7_TT_FS_trial1_60\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=204;%frame where cricket is first available
files(n).FrameEnd=1590;%frame where cricket is caught
files(n).CapTime=23;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey7_TT_60\Prey7_TT_FS_trial1_60.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey7_TT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey7_TT_60\Prey7_TT_FS_trial2_60\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=488;%frame where cricket is first available
files(n).FrameEnd=1126;%frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey7_TT_60\Prey7_TT_FS_trial2_60.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey9_RT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey9_RT\Prey9_RT_FS_trial4\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=2;
files(n).FrameS=283;%frame where cricket is first available
files(n).FrameEnd=1515;%frame where cricket is caught
files(n).CapTime=20;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey9_RT\Prey9_RT_FS_trial4.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey7_RT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey7_RT_60\Prey7_RT_FS_trial2\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=143;%frame where cricket is first available
files(n).FrameEnd=962;%frame where cricket is caught
files(n).CapTime=14;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey7_RT_60\Prey7_RT_FS_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey7_RT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey7_RT_60\Prey7_RT_FS_trial3_60\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=260;%frame where cricket is first available
files(n).FrameEnd=1452;%frame where cricket is caught
files(n).CapTime=20;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey7_RT_60\Prey7_RT_FS_trial3_60.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey7_RT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey7_RT_60\Prey7_RT_FS_trial4\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=301;%frame where cricket is first available
files(n).FrameEnd=2200;%frame where cricket is caught
files(n).CapTime=30;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_FS_3_12_16\Prey7_RT_60\Prey7_RT_FS_trial4.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey8_RT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_manip_3_14_16\Prey8_RT_1\Prey8_RT_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=2;
files(n).FrameS=4;%frame where cricket is first available
files(n).FrameEnd=700;%frame where cricket is caught
files(n).CapTime=12;
files(n).FrameFlash='';
files(n).Moviefile='Pre_manip_3_14_16\Prey8_RT_FS_trial2.avi';
files(n).body=0;

%%% sample used in figure 1 and Figure 2 in paper for light behavior
n=n+1;
files(n).subj = 'prey11_LT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_group3_3_17_16\Prey11_LT_pre_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=2;
files(n).FrameS=4;%frame where cricket is first available
files(n).FrameEnd=500;%frame where cricket is caught is 670
files(n).CapTime=8;
files(n).FrameFlash='';
files(n).Moviefile='Pre_group3_3_17_16\Prey11_LT_pre_FS_trial3.avi';
files(n).body=0;

% n=n+1;
% files(n).subj = 'prey9_LT';
% files(n).lighting = ON;
% files(n).trackpts = 'Pre_manip_FS_3_12_16\Prey9_LT\Prey9_LT_FS_trial2\tracks\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=1;
% files(n).sex=2;
% files(n).FrameS=239;%frame where cricket is first available
% files(n).FrameEnd=2819;%frame where cricket is caught
% files(n).CapTime=63;
% files(n).FrameFlash='';
% files(n).Moviefile='Pre_manip_FS_3_12_16\Prey9_LT\Prey9_LT_FS_trial2.avi';
% files(n).body=0;

n=n+1;
files(n).subj = 'prey14_NT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey14_preM_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=291;%frame where cricket is caught
files(n).CapTime=5;
files(n).FrameFlash='';
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey14_preM_FS_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey14_NT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey14_preM_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=2;
files(n).FrameS=48;%frame where cricket is first available
files(n).FrameEnd=670;%frame where cricket is caught
files(n).CapTime=10;
files(n).FrameFlash='';
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey14_preM_FS_trial3.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey10_LT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_group3_3_17_16\Prey10_LT_pre_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1472;%frame where cricket is caught
files(n).CapTime=25;
files(n).FrameFlash='';
files(n).Moviefile='Pre_group3_3_17_16\Prey10_LT_pre_FS_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey10_LT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_group3_3_17_16\Prey10_LT_pre_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1200;%frame where cricket is caught
files(n).CapTime=20;
files(n).FrameFlash='';
files(n).Moviefile='Pre_group3_3_17_16\Prey10_LT_pre_FS_trial3.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey11_NT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_group3_3_17_16\Prey11_NT_pre_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=30;%frame where cricket is first available
files(n).FrameEnd=436;%frame where cricket is caught
files(n).CapTime=7;
files(n).FrameFlash='';
files(n).Moviefile='Pre_group3_3_17_16\Prey11_NT_pre_FS_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey11_NT';
files(n).lighting = ON;
files(n).trackpts = 'Pre_group3_3_17_16\Prey11_NT_pre_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=560;%frame where cricket is caught
files(n).CapTime=9;
files(n).FrameFlash='';
files(n).Moviefile='Pre_group3_3_17_16\Prey11_NT_pre_FS_trial3.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey12';
files(n).lighting = ON;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey12_preM_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=460;%frame where cricket is first available
files(n).FrameEnd=1389;%frame where cricket is caught
files(n).CapTime=15;
files(n).FrameFlash='';
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey12_preM_FS_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey12';
files(n).lighting = ON;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey12_preM_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=953;%frame where cricket is caught
files(n).CapTime=16;
files(n).FrameFlash='';
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey12_preM_FS_trial3.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey13_ff';
files(n).lighting = ON;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey13ff_dark_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=23;%frame where cricket is first available
files(n).FrameEnd=365;%frame where cricket is caught
files(n).CapTime=6;
files(n).FrameFlash='';
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey13ff_dark_FS_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey13_ff';
files(n).lighting = ON;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey13ff_dark_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=1;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=119;%frame where cricket is caught
files(n).CapTime=2;
files(n).FrameFlash='';
files(n).Moviefile='Prey13ff_dark_FS_trial2.avi';
files(n).body=0;
%% Dark first exposure

n=n+1;
files(n).subj = 'prey7_RT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_15_16\Prey7_RT_dark_NIR_trial4\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=1;
files(n).FrameS=305;%frame where cricket is first available
files(n).FrameEnd=2250;%frame where cricket is caught
files(n).CapTime=33;
files(n).FrameFlash='';
files(n).Moviefile='Dark_1st_time_3_15_16\Prey7_RT_dark_NIR_trial4.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'prey7_RT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_15_16\Prey7_RT_dark_NIR_trial5\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=1;
files(n).FrameS=210;%frame where cricket is first available
files(n).FrameEnd=3050;%frame where cricket is caught
files(n).CapTime=47;
files(n).FrameFlash='';
files(n).Moviefile='Dark_1st_time_3_15_16\Prey7_RT_dark_NIR_trial5.avi';
files(n).body=1;


n=n+1;
files(n).subj = 'prey8_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_15_16\Prey8_NT_dark_NIR_trial1\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=230;%frame where cricket is first available
files(n).FrameEnd=2584;%frame where cricket is caught
files(n).CapTime=39;
files(n).FrameFlash='';
files(n).Moviefile='Dark_1st_time_3_15_16\Prey8_NT_dark_NIR_trial1.avi';
files(n).body=1;

%%used in figure 2 example
n=n+1;
files(n).subj = 'prey8_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_15_16\Prey8_NT_dark_NIR_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=270;%frame where cricket is first available
files(n).FrameEnd=2719;%frame where cricket is caught
files(n).CapTime=41;
files(n).FrameFlash='';
files(n).Moviefile='Dark_1st_time_3_15_16\Prey8_NT_dark_NIR_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'prey11_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_17_16_group2\Prey11_NT_dark_NIR_trial4\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=1;
files(n).FrameS=2087;%frame where cricket is first available
files(n).FrameEnd=5230;%frame where cricket is caught
files(n).CapTime=52;
files(n).FrameFlash='';
files(n).Moviefile='Dark_1st_time_3_17_16_group2\Prey11_NT_dark_NIR_trial4.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'prey11_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_17_16_group2\Prey11_NT_dark_NIR_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=1;
files(n).FrameS=282;%frame where cricket is first available
files(n).FrameEnd=815;%frame where cricket is caught
files(n).CapTime=9;
files(n).FrameFlash='';
files(n).Moviefile='Dark_1st_time_3_17_16_group2\Prey11_NT_dark_NIR_trial2.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'prey14_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey14_dark_NIR_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=87;%frame where cricket is first available
files(n).FrameEnd=5473;%frame where cricket is caught
files(n).CapTime=90;
files(n).FrameFlash=''
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey14_dark_NIR_trial3.avi'
files(n).body=0;

n=n+1;
files(n).subj = 'prey14_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey14_dark_NIR_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=996;%frame where cricket is caught
files(n).CapTime=17;
files(n).FrameFlash=''
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey14_dark_NIR_trial2.avi'
files(n).body=0;


n=n+1;
files(n).subj = 'prey10_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_17_16_group2\Prey10_NT_NIR_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=1182;%frame where cricket is caught
files(n).CapTime=20;
files(n).FrameFlash=''
files(n).Moviefile='Dark_1st_time_3_17_16_group2\Prey10_NT_NIR_trial1.avi'
files(n).body=0;

n=n+1;
files(n).subj = 'prey10_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_17_16_group2\Prey10_NT_NIR_trial4\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=1;
files(n).FrameS=757;%frame where cricket is first available
files(n).FrameEnd=2374;%frame where cricket is caught
files(n).CapTime=27;
files(n).FrameFlash=''
files(n).Moviefile='Dark_1st_time_3_17_16_group2\Prey10_NT_NIR_trial4.avi'
files(n).body=0;

n=n+1;
files(n).subj = 'prey8_RTp';
files(n).lighting = OFF;
files(n).trackpts = 'Dark_1st_time_3_15_16\Prey8_RT_p_dark_NIR_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=252;%frame where cricket is first available
files(n).FrameEnd=936;%frame where cricket is caught
files(n).CapTime=11;
files(n).FrameFlash=''
files(n).Moviefile='Dark_1st_time_3_15_16\Prey8_RT_p_dark_NIR_trial2.avi'
files(n).body=0;

% n=n+1;
% files(n).subj = 'prey8_RTp';
% files(n).lighting = OFF;
% files(n).trackpts = 'Dark_1st_time_3_15_16\Prey8_RT_p_dark_NIR_trial3\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=2;
% files(n).sex=2;
% files(n).FrameS=301;%frame where cricket is first available
% files(n).FrameEnd=446;%frame where cricket is caught 
% files(n).CapTime=3;
% files(n).FrameFlash=''; %missing 353-357 points from cricket tracking
% files(n).Moviefile='Dark_1st_time_3_15_16\Prey8_RT_p_dark_NIR_trial3.avi';
% files(n).body=0;

%not tracked properly
% n=n+1;
% files(n).subj = 'prey12_';
% files(n).lighting = OFF;
% files(n).trackpts = 'trial2\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=2;
% files(n).sex=2;
% files(n).FrameS=;%frame where cricket is first available
% files(n).FrameEnd=;%frame where cricket is caught
% files(n).FrameFlash=''
% files(n).Moviefile='_trial2.avi'
% files(n).body=0;

n=n+1;
files(n).subj = 'prey12';
files(n).lighting = OFF;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\prey12_dark_NIR_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=3600;%frame where cricket is caught
files(n).CapTime=74;
files(n).FrameFlash=''
files(n).Moviefile='Pre_Manip_Group3_4_30_16\prey12_dark_NIR_trial3.avi'
files(n).body=0;

n=n+1;
files(n).subj = 'prey13';
files(n).lighting = OFF;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey13ff_dark_NIR_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=1349;%frame where cricket is caught
files(n).CapTime=22;
files(n).FrameFlash=''
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey13ff_dark_NIR_trial1.avi'
files(n).body=0;

n=n+1;
files(n).subj = 'prey13';
files(n).lighting = OFF;
files(n).trackpts = 'Pre_Manip_Group3_4_30_16\Prey13ff_dark_NIR_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=2;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=1350;%frame where cricket is caught
files(n).CapTime=23;
files(n).FrameFlash=''
files(n).Moviefile='Pre_Manip_Group3_4_30_16\Prey13ff_dark_NIR_trial2.avi'
files(n).body=0;

%% eye suture first exposure
n=n+1;
files(n).subj = 'prey7_LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_LT_FS_ES_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=245;%frame where cricket is first available
files(n).FrameEnd=2390;%frame where cricket is caught
files(n).CapTime=70;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_LT_FS_ES_trial1.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'prey7_LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_LT_FS_ES_trial4\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=275;%frame where cricket is first available
files(n).FrameEnd=1200;%frame where cricket is caught
files(n).CapTime=15;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_LT_FS_ES_trial4.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey7_LT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_LT_NIR_ES_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=211;%frame where cricket is first available
files(n).FrameEnd=964;%frame where cricket is caught 
files(n).CapTime=13;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_LT_NIR_ES_trial3.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey7_LT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_LT_NIR_ES_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=315;%frame where cricket is first available
files(n).FrameEnd=1704;%frame where cricket is caught
files(n).CapTime=20;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_LT_NIR_ES_trial2.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey9_LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey9_LT_FS_ES_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=200;%frame where cricket is first available
files(n).FrameEnd=3080;%frame where cricket is caught
files(n).CapTime=180;%48
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey9_LT_FS_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey7_TT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_TT_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=229;%frame where cricket is first available
files(n).FrameEnd=3727;%frame where cricket is caught
files(n).CapTime=54;%58
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_TT_FS_trial3.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey7_TT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_TT_NIR_trial5\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=246;%frame where cricket is first available
files(n).FrameEnd=3015;%frame where cricket is caught
files(n).CapTime=50;%46
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_TT_NIR_trial5.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey7_TT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_TT_NIR_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=500;%frame where cricket is first available
files(n).FrameEnd=3400;%frame where cricket is caught
files(n).CapTime=145;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_TT_NIR_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey9_RT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey9_RT_FS_ES_trial4\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=2;
files(n).FrameS=267;%frame where cricket is first available
files(n).FrameEnd=1881;%frame where cricket is caught
files(n).CapTime=27;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey9_RT_FS_ES_trial4.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey9_RT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey9_RT_FS_ES_trial7\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=2;
files(n).FrameS=160;%frame where cricket is first available
files(n).FrameEnd=2100;%frame where cricket is caught
files(n).CapTime=35;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey9_RT_FS_ES_trial7.avi';
files(n).body=0;


n=n+1;
files(n).subj = 'Prey9_RT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey9_RT_NIR_ES_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=2;
files(n).FrameS=338;%frame where cricket is first available
files(n).FrameEnd=2012;%frame where cricket is caught
files(n).CapTime=30;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey9_RT_NIR_ES_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey7_TT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_TT_NIR_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=335;%frame where cricket is first available
files(n).FrameEnd=5810;%frame where cricket is caught
files(n).CapTime=91;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_TT_NIR_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey9_RT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey9_RT_NIR_ES_trial5\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=400;%frame where cricket is first available
files(n).FrameEnd=1520;%frame where cricket is caught
files(n).CapTime=19;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey9_RT_NIR_ES_trial5.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey7_LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_LT_FS_ES_trial5\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=325;%frame where cricket is first available
files(n).FrameEnd=4394;%frame where cricket is caught
files(n).CapTime=68;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_LT_FS_ES_trial5.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey7_LT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_LT_NIR_trial6\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=260;%frame where cricket is first available
files(n).FrameEnd=2007;%frame where cricket is caught
files(n).CapTime=29;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_LT_NIR_trial6.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey7_TT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_3_15_16\Prey7_TT_FS_trial6\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;%eye suture group
files(n).sex=1;
files(n).FrameS=390;%frame where cricket is first available
files(n).FrameEnd=2273;%frame where cricket is caught
files(n).CapTime=31;
files(n).FrameFlash='';
files(n).Moviefile='Eye_suture_3_15_16\Prey7_TT_FS_trial6.avi';
files(n).body=0;

%% 1st batch C:\Users\nlab\Desktop\Prey Capture track Data Eyre\Prey_tracks\'
n=n+1;
files(n).subj = 'prey4-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey4_LT_trial2\Prey4_LT_ES_FS_trial2_2_8_16.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=2782;%frame where cricket is caught
files(n).CapTime=46;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
n=n+1;
files(n).subj = 'prey4-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey4_LT_trial4\Prey4_LT_ES_FS_trial4_2_8_16.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1302;%frame where cricket is caught
files(n).CapTime=22;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
n=n+1;
files(n).subj = 'prey4-LT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_1st_batch\Prey4_LT_trial3_NIR\Prey4_LT_ES_NIR_trial3_2_8_16.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=2621;%frame where cricket is caught
files(n).CapTime=44;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
n=n+1;
files(n).subj = 'prey4-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey4_LT_trial5\Prey4_LT_ES_FS_trial5_2_8_16.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=3703;%frame where cricket is caught
files(n).CapTime=62;%43
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
n=n+1;
files(n).subj = 'prey4-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey4_LT_trial6\Prey4_LT_ES_FS_trial6_2_8_16.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1063;%frame where cricket is caught
files(n).CapTime=18;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
n=n+1;
files(n).subj = 'prey4-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey4_LT_trial7\Prey4_LT_FS_ES_trial7.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=2253;%frame where cricket is caught
files(n).CapTime=38;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% %
% n=n+1;
% files(n).subj = 'prey4-TT';
% files(n).lighting = OFF;
% files(n).trackpts = 'Eye_suture_1st_batch\Prey4_TT_trial1\Prey4_TT_NIR_ES_trial1_noBody.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 50;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=3;
% files(n).sex=2;
% files(n).FrameS=1;%frame where cricket is first available
% files(n).FrameEnd=810;%frame where cricket is caught
% files(n).CapTime=14;
% files(n).FrameFlash='';
% files(n).Moviefile='';
% files(n).body=0;
% % 
% n=n+1;
% files(n).subj = 'prey4-TT';
% files(n).lighting = ON;
% files(n).trackpts = 'Eye_suture_1st_batch\Prey4_TT_trial1_FS\Prey4_TT_FS_ES_trial1.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 50;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=3;
% files(n).sex=2;
% files(n).FrameS=1;%frame where cricket is first available
% files(n).FrameEnd=808;%frame where cricket is caught
% files(n).FrameFlash='';
% files(n).Moviefile='';
% files(n).body=1;
% % 
% n=n+1;
% files(n).subj = 'prey4-TT';
% files(n).lighting = OFF;
% files(n).trackpts = 'Eye_suture_1st_batch\Prey4_TT_trial4_NIR\Prey4_TT_NIR_ES_trial4_noBody.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 50;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=3;
% files(n).sex=2;
% files(n).FrameS=1;%frame where cricket is first available
% files(n).FrameEnd=838;%frame where cricket is caught
% files(n).CapTime=14;
% files(n).FrameFlash='';
% files(n).Moviefile='';
% files(n).body=0;
% 
n=n+1;
files(n).subj = 'prey5-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey5_LT_trial1\Prey5_LT_ES_FS_trial1.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1137;%frame where cricket is caught
files(n).CapTime=19;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
n=n+1;
files(n).subj = 'prey5-LT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_1st_batch\Prey5_LT_trial1_NIR\Prey5_LT_ES_NIR_trial1.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=821;%frame where cricket is caught
files(n).CapTime=14;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
n=n+1;
files(n).subj = 'prey5-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey5_LT_trial2\Prey5_LT_ES_FS_trial2.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=2049;%frame where cricket is caught
files(n).CapTime=34;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;
% 
% 
n=n+1;
files(n).subj = 'prey5-LT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_1st_batch\Prey5_LT_trial3_NIR\Prey5_LT_ES_NIR_trial3.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=3400;%frame where cricket is caught
files(n).CapTime=55;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;


n=n+1;
files(n).subj = 'prey5-LT';
files(n).lighting = OFF;
files(n).trackpts = 'Eye_suture_1st_batch\Prey5_LT_trial5_NIR\Prey5_LT_ES_NIR_trial5.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=607;%frame where cricket is caught
files(n).CapTime=10;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;


n=n+1;
files(n).subj = 'prey5-LT';
files(n).lighting = ON;
files(n).trackpts = 'Eye_suture_1st_batch\Prey5_LT_trial6\Prey5_LT_ES_FS_trial6.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 50;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=3;
files(n).sex=1;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1204;%frame where cricket is caught
files(n).CapTime=20;
files(n).FrameFlash='';
files(n).Moviefile='';
files(n).body=1;


%% ear plug first exposure

n=n+1;
files(n).subj = 'Prey7_RT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey7_RT_EP_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=1;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=966;%frame where cricket is caught
files(n).CapTime=16;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey7_RT_EP_FS_trial3.avi';
files(n).body=1;


n=n+1;
files(n).subj = 'Prey7_RT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey7_RT_EP_FS_trial4\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=1;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=190;%frame where cricket is caught
files(n).CapTime=3;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey7_RT_EP_FS_trial4.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey8_RT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey8_RT_EP_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=845;%frame where cricket is caught
files(n).CapTime=14;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey8_RT_EP_FS_trial1.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey8_RT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey8_RT_EP_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=920;%frame where cricket is caught
files(n).CapTime=16;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey8_RT_EP_FS_trial2.avi';
files(n).body=1;


n=n+1;
files(n).subj = 'Prey7_NT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey7_NT_EP_FS_trial5\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=1;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=1741;%frame where cricket is caught
files(n).CapTime=29;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey7_NT_EP_FS_trial5.avi';
files(n).body=0;


n=n+1;
files(n).subj = 'Prey7_NT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey7_NT_EP_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=1;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=2094;%frame where cricket is caught
files(n).CapTime=35;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey7_NT_EP_FS_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey8_RTp';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey8_RTp_EP_FS_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=1750;%frame where cricket is caught
files(n).CapTime=29;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey8_RTp_EP_FS_trial3.avi';
files(n).body=0;


n=n+1;
files(n).subj = 'Prey8_RTp';
files(n).lighting = ON;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey8_RTp_EP_FS_trial4\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=470;%frame where cricket is caught
files(n).CapTime=8;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey8_RTp_EP_FS_trial4.avi';
files(n).body=0;


n=n+1;
files(n).subj = 'Prey15_PT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey15_PT_EP_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=519;%frame where cricket is caught
files(n).CapTime=9;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey15_PT_EP_FS_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey15_PT';
files(n).lighting = ON;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey15_PT_EP_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=945;%frame where cricket is caught
files(n).CapTime=16;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey15_PT_EP_FS_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey12_p';
files(n).lighting = ON;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey12_P_EP_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1920;%frame where cricket is caught
files(n).CapTime=32;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey12_P_EP_FS_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey12_p';
files(n).lighting = ON;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey12_P_EP_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1786;%frame where cricket is caught
files(n).CapTime=30;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey12_P_EP_FS_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey13_NTp';
files(n).lighting = ON;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey13_NT_EP_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=10;%frame where cricket is first available
files(n).FrameEnd=1100;%frame where cricket is caught
files(n).CapTime=18;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey13_NT_EP_FS_trial1.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey13_NTp';
files(n).lighting = ON;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey13_NT_EP_FS_trial2\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1007;%frame where cricket is caught
files(n).CapTime=16;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey13_NT_EP_FS_trial2.avi';
files(n).body=0;

%% ear plug dark
n=n+1;
files(n).subj = 'Prey7_RT';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey7_RT_EP_NIR_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;%ear plug
files(n).sex=1;
files(n).FrameS=10;%frame where cricket is first available
files(n).FrameEnd=7200;%frame where cricket is caught
files(n).CapTime=390;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey7_RT_EP_NIR_trial1.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey8-RTp';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey8_RTp_EP_NIR_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;%ear plug
files(n).sex=2;
files(n).FrameS=4;%frame where cricket is first available
files(n).FrameEnd=2000;%frame where cricket is caught
files(n).CapTime=70;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey8_RTp_EP_NIR_trial1.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey7_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_plug_group2_3_17_16\Prey7_NT_EP_NIR_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;%ear plug
files(n).sex=1;
files(n).FrameS=4;%frame where cricket is first available
files(n).FrameEnd=3880;%frame where cricket is caught
files(n).CapTime=120;
files(n).FrameFlash='';
files(n).Moviefile='Ear_plug_group2_3_17_16\Prey7_NT_EP_NIR_trial3.avi';
files(n).body=1;


n=n+1;
files(n).subj = 'Prey15';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey15_PT_EP_NIR_trial5\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;%ear plug
files(n).sex=1;
files(n).FrameS=108;%frame where cricket is first available
files(n).FrameEnd=1670;%frame where cricket is caught
files(n).CapTime=28;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey15_PT_EP_NIR_trial5.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey12p';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey12_P_EP_NIR_trial3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;%ear plug
files(n).sex=1;
files(n).FrameS=5;%frame where cricket is first available
files(n).FrameEnd=3672;%frame where cricket is caught
files(n).CapTime=303;%61
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey12_P_EP_NIR_trial3.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey12p';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey12_P_EP_NIR_trial5B\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;%ear plug
files(n).sex=1;
files(n).FrameS=45;%frame where cricket is first available
files(n).FrameEnd=3612;%frame where cricket is caught
files(n).CapTime=323;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey12_P_EP_NIR_trial5B.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey13_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey13_NT_EP_NIR_trial2\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=1975;%frame where cricket is caught
files(n).CapTime=33;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey13_NT_EP_NIR_trial2.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey13_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey13_NT_EP_NIR_trial4\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=10;%frame where cricket is first available
files(n).FrameEnd=3600;%frame where cricket is caught
files(n).CapTime=300;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey13_NT_EP_NIR_trial4.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey15_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey15_PT_EP_NIR_trial6\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=2275;%frame where cricket is caught
files(n).CapTime=38;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey15_PT_EP_NIR_trial6.avi';
files(n).body=0;

n=n+1;
files(n).subj = 'Prey15_NT';
files(n).lighting = OFF;
files(n).trackpts = 'Ear_Plug_5_11_16\Prey15_PT_EP_NIR_trial7\Tracks\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;
files(n).sex=2;
files(n).FrameS=1;%frame where cricket is first available
files(n).FrameEnd=3660;%frame where cricket is caught
files(n).CapTime=240;
files(n).FrameFlash='';
files(n).Moviefile='Ear_Plug_5_11_16\Prey15_PT_EP_NIR_trial7.avi';
files(n).body=0;

%% BLK Bgd

n=n+1;
files(n).subj = 'Prey8_RT';
files(n).lighting = ON;
files(n).trackpts = 'Bbgd_3_29_16\Prey8_RT_FS_trial1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=4;%blkBgd
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=1876;%frame where cricket is caught
files(n).CapTime=31;
files(n).FrameFlash='';
files(n).Moviefile='Bbgd_3_29_16\Prey8_RT_FS_trial1.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey8_RTp';
files(n).lighting = ON;
files(n).trackpts = 'Bbgd_3_29_16\Prey8_RTP_FS_trial_3\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=4;%blkBgd
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=1048;%frame where cricket is caught
files(n).CapTime=17;
files(n).FrameFlash='';
files(n).Moviefile='Bbgd_3_29_16\Prey8_RTP_FS_trial_3.avi';
files(n).body=1;

n=n+1;
files(n).subj = 'Prey7_TT';
files(n).lighting = ON;
files(n).trackpts = 'Bbgd_3_30_16\Prey7_TT_FS_trial_1\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=4;%blkBgd
files(n).sex=1;
files(n).FrameS=4;%frame where cricket is first available
files(n).FrameEnd=3245;%frame where cricket is caught
files(n).CapTime=54;%54
files(n).FrameFlash='';
files(n).Moviefile='Bbgd_3_30_16\Prey7_TT_FS_trial_1.avi';
files(n).body=1;

%% analyzed 3,500 frames to start
n=n+1;
files(n).subj = 'Prey8_RT';
files(n).lighting = OFF;
files(n).trackpts = 'Bbgd_3_29_16\Prey8_RT_NIR_trial4\DLTdv5_data_xypts.csv';
files(n).soundfile = '';
files(n).headbar = 0;
files(n).contrast = 100;
files(n).notes = '';
files(n).fps=60;
files(n).scale=35;%pixels/cm on video tracking
files(n).group=5;%blkBgd but included in ear plug group white background
files(n).sex=2;
files(n).FrameS=3;%frame where cricket is first available
files(n).FrameEnd=4188;%sample,only 4188 points included in track data, 7200 long total video
files(n).CapTime=480;%70
files(n).FrameFlash='';
files(n).Moviefile='Bbgd_3_29_16\Prey8_RT_NIR_trial4.avi';
files(n).body=1;

% n=n+1;
% files(n).subj = 'Prey7_TT';
% files(n).lighting = ON;
% files(n).trackpts = 'Plexiglass_whitebgd_4_5_16\Prey7_TTearplug_trial_1_rightside_FS\Tracks\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=6;%plexitrials
% files(n).sex=2;
% files(n).FrameS=3;%frame where cricket is first available
% files(n).FrameEnd=3007%sample,only 4188 points included in track data, 7200 long total video
% files(n).FrameFlash='';
% files(n).Moviefile='Plexiglass_whitebgd_4_5_16\Prey7_TTearplug_trial_1_rightside_FS.avi';
% files(n).body=0;
% 
% n=n+1;
% files(n).subj = 'Prey7_TT';
% files(n).lighting = OFF;
% files(n).trackpts = 'Plexiglass_whitebgd_4_5_16\Prey7_TTearplug_trial_3_rightside_NIR\Tracks\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=6;%blkBgd but included in ear plug group white background
% files(n).sex=2;
% files(n).FrameS=3;%frame where cricket is first available
% files(n).FrameEnd=3005%sample,only 4188 points included in track data, 7200 long total video
% files(n).FrameFlash='';
% files(n).Moviefile='Plexiglass_whitebgd_4_5_16\Prey7_TTearplug_trial_3_rightside_NIR.avi';
% files(n).body=0;
% 
% n=n+1;
% files(n).subj = 'Prey11_RT';
% files(n).lighting = ON;
% files(n).trackpts = 'Plexiglass_3_18_16\Prey11_RT_PG_FS_trial1_RS\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=6;%blkBgd but included in ear plug group white background
% files(n).sex=2;
% files(n).FrameS=2;%frame where cricket is first available
% files(n).FrameEnd=2900%sample,only 4188 points included in track data, 7200 long total video
% files(n).FrameFlash='';
% files(n).Moviefile='Plexiglass_3_18_16\Prey11_RT_PG_FS_trial1_RS.avi';
% files(n).body=0;
% 
% n=n+1;
% files(n).subj = 'Prey12_PT';
% files(n).lighting = OFF;
% files(n).trackpts = 'Plexiglass_5_31_16\Prey_12_PT_trial_1_LS_NIR\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=6;%blkBgd but included in ear plug group white background
% files(n).sex=2;
% files(n).FrameS=3;%frame where cricket is first available
% files(n).FrameEnd=2000
% files(n).FrameFlash='';
% files(n).Moviefile='Plexiglass_5_31_16\Prey_12_PT_trial_1_LS_NIR.avi';
% files(n).body=0;
% 
% n=n+1;
% files(n).subj = 'Prey12_PT';
% files(n).lighting = ON;
% files(n).trackpts = 'Plexiglass_5_31_16\Prey_12_PT_trial_2_LS_FS\DLTdv5_data_xypts.csv';
% files(n).soundfile = '';
% files(n).headbar = 0;
% files(n).contrast = 100;
% files(n).notes = '';
% files(n).fps=60;
% files(n).scale=35;%pixels/cm on video tracking
% files(n).group=6;%blkBgd but included in ear plug group white background
% files(n).sex=1;
% files(n).FrameS=355;%frame where cricket is first available
% files(n).FrameEnd=2526;%
% files(n).FrameFlash='';
% files(n).Moviefile='Plexiglass_5_31_16\Prey_12_PT_trial_2_LS_FS.avi';
% files(n).body=0;
