dbstop if error

afile = {   'E:\jennifer\Jennifer_analysis\NR2B\3_25_15\analysis_2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\3_26_15\full\analysis_2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\4_23_15\analysis_2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_18_15\analysis_2A.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_22_15\analysis_2A.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_23_15\analysis_2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_26_15\analysis_2A.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\7_1_15\analysis_2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_11_15\analysis_2A.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_11_15_rec2\analysis_2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_13_15\analysis_2A.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_13_15_rec2\analysis_2A.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_14_15\analysis.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_19_15_full\analysis_2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_19_15_Rec2\analysis_2.mat'};                       

clusterfilenames= { 'E:\jennifer\Jennifer_analysis\NR2B\3_25_15\cluster_data_3_25_15_full.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\3_26_15\full\cluster_data_3_26_15_full.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\4_23_15\cluster_data_4_23_15_NR2B_KO.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_18_15\cluster_data_6_18_15_KO.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_22_15\cluster_data_6_22_15_KO.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_23_15\cluster_data_6_23_15_Ko.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\6_26_15\cluster_data_6_26_15_2B_KO.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\7_1_15\cluster_data_7_1_15_2B_KO.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_11_15\cluster_data_8_11_15_2B.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_11_15_rec2\cluster_data_8_11_15_2B_rec2.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_13_15\cluster_data_8_13_15_2B.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_13_15_rec2\cluster_data_8_13_15_2B.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_14_15\cluster_data_8_14_15_2B.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_19_15_full\cluster_data_8_19_15_N2B.mat',...
            'E:\jennifer\Jennifer_analysis\NR2B\8_19_15_Rec2\cluster_data_8_19_15_n2b_rec2.mat'};               % MLRstim #16}



for i = 1:length(afile);
    i
    afile
    
    analysisFile = afile{i};
    load(analysisFile);
   
    clusterFile = clusterfilenames{i};
    load(clusterFile);
    
%     [fname pname] = uigetfile('*.mat','cluster file');
%      clusterFile = fullfile(pname,fname);
%      clusterfilename = clusterFile;     
%      save(analysisFile,'clusterfilename','-append');
  
  
   
    for i = 1:length(Block_Name)
        if strcmp('sp',Block_Name{i}(1:2)) %'sp' if spot analysis 'wn' if cm_noise
            blocknum=i;
        end
    end
    pdfname = [analysisFile(1:end-4) '.pdf'];
    
    
movieFile = 'C:\Users\nlab\Desktop\movie files\cortex\sparse20%6x_flash031312.mat';
load(movieFile);
    

    %pptgSpeedAnalysis(clusterFile,analysisFile,pdfname,Block_Name{blocknum},blocknum,1, 30);
    noise_analysis(clusterFile,analysisFile,pdfname,movieFile,Block_Name{blocknum},blocknum,2, 1)
% movietype==fl_noise==2; 
% movietype==cm_noise==1 
% movietype==mv_noise==3
    toc

    %plot(vdata)
    end
    