afile = {...
    'D:\Jen_ephys_data\developmental_periods\Good recordings\EO7_EO9\P24_9_11_14\analysis_9_11_14_rec1.mat',...
     'D:\Jen_ephys_data\developmental_periods\Good recordings\EO7_EO9\P24_9_11_14\rec2\analysis_9_11_14_rec2.mat',...
     'D:\Jen_ephys_data\developmental_periods\Good recordings\EO7_EO9\9_30_14_EO9\analysis_9_30_14_EO9_rec1.mat',...
     'D:\Jen_ephys_data\developmental_periods\Good recordings\EO7_EO9\10_2_14_EO5\rec1\analysis_10_2_14_rec1_EO5.mat',...
     'D:\Jen_ephys_data\developmental_periods\Good recordings\EO3_EO4\10_1_14_EO4\analysis_10_1_14_rec1_EO4_Altered.mat',...
    'D:\Jen_ephys_data\developmental_periods\Good recordings\EO3_EO4\10_1_14_EO4\rec2\analysis_10_1_14_rec2_EO4.mat',...
   'D:\Jen_ephys_data\developmental_periods\Good recordings\EO3_EO4\EO3_9_24_14\analysis_9_24_14_EO3.mat',... 
  'D:\Jen_ephys_data\developmental_periods\Good recordings\EO3_EO4\EO4_9_25_14_rec1\analysis_9_25_14_EO4_rec1.mat',...
  'D:\Jen_ephys_data\developmental_periods\Good recordings\EO3_EO4\EO4_9_25_14_rec1\rec2\analysis_9_25_14_EO4_rec2.mat',...
  }     

tic
for i = 1:length(afile)
    i
analysisFile = afile{i};
%     afile = fullfile(pname,fname)
    load(analysisFile)

    
    %%renamming proceurehere
[drift.osi] = drift.cv_osi;
drift = rmfield(drift,'cv_osi');
disp(drift)

[drift.dsi] = drift.cv_dsi;
drift = rmfield(drift,'cv_dsi');
disp(drift)

save(analysisFile,'drift','-append');

end