n=0;

afile = {    'C:\data\lgn rf project\lgn_analysis\030912_rec3_analysis3_final.mat',...
    'C:\data\lgn rf project\lgn_analysis\030912_rec4_analysis_4final.mat',...
    'C:\data\lgn rf project\lgn_analysis\031012_analysis1check.mat',...
    'C:\data\lgn rf project\lgn_analysis\031012_analysis2check.mat',...
    'C:\data\lgn rf project\lgn_analysis\031512_analysis2check.mat',...
    'C:\data\lgn rf project\lgn_analysis\031512_analysis3check.mat',...
    'C:\data\lgn rf project\lgn_analysis\031612_analysis1checkb.mat',...
    'C:\data\lgn rf project\lgn_analysis\031612_analysischeck2b.mat',...
    'C:\data\lgn rf project\lgn_analysis\031612_analysis3check.mat', ...
    'C:\data\lgn rf project\lgn_analysis\052512_analysis1check.mat',...
    'C:\data\lgn rf project\lgn_analysis\060112_analysis1check.mat',...
    'C:\data\lgn rf project\lgn_analysis\060712_analysis1check.mat',...
    'C:\data\lgn rf project\lgn_analysis\060812_analysis1check.mat',...
    'C:\data\lgn rf project\lgn_analysis\061212_analysis1check.mat',...
    'C:\data\lgn rf project\lgn_analysis\061212_analysis2check.mat',...
    'C:\data\lgn rf project\lgn_analysis\062212_analysis3check.mat',...
    'C:\data\lgn rf project\lgn_analysis\062212_analysis4check.mat',...
    'C:\data\lgn rf project\lgn_analysis\071612_analysis1new.mat', ...
    'C:\data\lgn rf project\lgn_analysis\071712_analysis1new.mat' ...
    'C:\data\lgn rf project\lgn_analysis\071712_analysis2new.mat' ...
    'C:\data\lgn rf project\lgn_analysis\071812_analysis1new.mat' ...
    'C:\data\lgn rf project\lgn_analysis\071812_analysis2new.mat' ...
    'C:\data\lgn rf project\lgn_analysis\072012_analysis1newst.mat' ...
    'C:\data\lgn rf project\lgn_analysis\072012_analysis2new.mat' ...
    'C:\data\lgn rf project\lgn_analysis\072012_analysis3.mat' ...
    'C:\data\lgn rf project\lgn_analysis\072412_analysis1.mat' ...
    'C:\data\lgn rf project\lgn_analysis\072512_analysis1.mat' ...
    'C:\data\lgn rf project\lgn_analysis\072512_ANALYSIS2.mat' ...
    'C:\data\lgn rf project\lgn_analysis\080212_analysis1.mat' ...
    'C:\data\lgn rf project\lgn_analysis\080212_analysis3.mat' ...
    'C:\data\lgn rf project\lgn_analysis\080312_analysis2.mat' ...
    'C:\data\lgn rf project\lgn_analysis\080312_analysis3bnew.mat' };



for i = 1:length(afile)
    analysisFile = afile{i};
    load(analysisFile);
    clusterFile = clusterfilename((length(pname)+1):end);
    load(clusterFile);
    for i = 1:length(Block_Name)
        if strcmp('wn',Block_Name{i}(1:2))
            blocknum=i;
        end
    end
    
    flags = struct('visStim',1);
    
    
    data = getTDTdata(Tank_Name,Block_Name{i},1:4:max(cells(:,1)),flags);
    
    % blockdata.mouseT = data.mouseT;
    % blockdata.mouseV = data.mouseV;
    exptdata(i).block = Block_Name;
    exptdata(i).tank = Tank_Name;
    exptdata(i).analysis_file = afile;
    exptdata(i).cluster_file = clustfile;
    exptdata(i).stimEpocs=data.stimEpocs;
    exptdata(i).frameEpocs = data.frameEpocs;
    
    for cell_n = 1:size(cells,1);
        unitdata.spikes{cell_n+n} =spikeT{cell_n}(spikeT{cell_n}>(blocknum-1)*10^5 & spikeT{cell_n}<(blocknum-1 + 0.5)*10^5) - (blocknum-1)*10^5;
        unitdata.expnum{cell_n+n} = i;
        %     blockdata.lfpT{cell_n} = data.lfpT{cells(cell_n,1)};
        %     blockdata.lfpV{cell_n} = data.lfpData{cells(cell_n,1)};
    end
    n=n+size(cells,1);
end

manual_outside = xlsread('C:\data\lgn rf project_new0824\lgn_analysis\lgn types 091412.xlsx','B1:B294');
manual_outside(isnan(manual_outside))=0;
outsideLGN = manual_outside;
load('C:\data\movie files\wn016alpha1_10hzLg60Hz.mat');

save('Piscopo_wn_data','exptdata','unitdata','outsideLGN','moviedata');