function layer_bar_median_new(data,used,exc,inh,layertwo,layerthree,layerfour,layerfive,layersix)
figure
barweb([median(data(used&exc&layertwo)) median(data(used&exc&layerthree)) median(data(used&exc&layerfour)) median(data(used&exc&layerfive)) median(data(used&exc&layersix));...
    median(data(used&inh&layertwo)) median(data(used&inh&layerthree)) median(data(used&inh&layerfour)) median(data(used&inh&layerfive)) median(data(used&inh&layersix))]', ...
    [med_se(data(used&exc&layertwo)) med_se(data(used&exc&layerthree)) med_se(data(used&exc&layerfour)) ...
    med_se(data(used&exc&layerfive)) med_se(data(used&exc&layersix));
     med_se(data(used&exc&layertwo)) med_se(data(used&exc&layerthree)) med_se(data(used&exc&layerfour)) ...
    med_se(data(used&exc&layerfive)) med_se(data(used&exc&layersix))  ]', ...
    [],[],[],[],[],[0 0.75 0; 0 0 0.75]);
set(gca,'xticklabel', {'upper 2/3', 'lower 2/3', '4', '5' '6'})
set(gca,'FontSize',14)
