function layer_bar_median(data,used,exc,inh,layertwo,layerthree,layerfour,layerfive,layersix)
figure
barweb([median(data(used&exc&layertwo)) median(data(used&exc&layerthree)) median(data(used&exc&layerfour)) median(data(used&exc&layerfive)) median(data(used&exc&layersix));...
    median(data(used&inh&layertwo)) median(data(used&inh&layerthree)) median(data(used&inh&layerfour)) median(data(used&inh&layerfive)) median(data(used&inh&layersix))]', ...
    ([std(data(used&exc&layertwo))/sqrt(sum(used&exc&layertwo )) std(data(used&exc&layerthree))/sqrt(sum(used&exc&layerthree))   ...
    std(data(used&exc&layerfour))/sqrt(sum(used&exc&layerfour )) std(data(used&exc&layerfive))/sqrt(sum(used&exc&layerfive )) std(data(used&exc&layersix))/sqrt(sum(used&exc&layersix )); ...
    std(data(used&inh&layertwo))/sqrt(sum(used&inh&layertwo )) std(data(used&inh&layerthree))/sqrt(sum(used&inh&layerthree )) ...
    std(data(used&inh&layerfour))/sqrt(sum(used&inh&layerfour )) std(data(used&inh&layerfive))/sqrt(sum(used&inh&layerfive )) std(data(used&inh&layersix))/sqrt(sum(used&inh&layersix ))]'), ...
    [],[],[],[],[],[0 0.75 0; 0 0 0.75]);
set(gca,'xticklabel', {'upper 2/3', 'lower 2/3', '4', '5' '6'})
set(gca,'FontSize',14)
