pathname = '\\angie\Angie_analysis\DOI_experiments';
n=0;


n=n+1;
files(n).expt = '081516';
files(n).dir = '08_15_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_15_16_cluster_081516';
files(n).analysisfile = 'analysis_081516';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = 'Lisuride'; %actually lisuride
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '4 mg/kg'; 
files(n).tip1 = 770; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '081216';
files(n).dir = '08_12_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_12_16_cluster_081216';
files(n).analysisfile = 'analysis_081216';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '10 mg/kg'; 
files(n).tip1 = 770; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [2 3 4 7 8];

%Ian's recording
n=n+1;
files(n).expt = '081116';
files(n).dir = '08_11_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_11_16_cluster_081116';
files(n).analysisfile = 'analysis_081116';
files(n).predark = 'darkness_pre02';
files(n).postdark = 'darkness_post02';
files(n).prewn = 'wn_pre01';
files(n).postwn = 'wn_post01';  
files(n).predrift = 'gratings_pre01';
files(n).postdrift = 'gratings_post01';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = 'Lisuride'; %actually lisuride
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; %Ian did recording 
files(n).misc = '4 mg/kg'; 
files(n).tip1 = 750; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '081016';
files(n).dir = '08_10_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_10_16_cluster_081016';
files(n).analysisfile = 'analysis_081016';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn _pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Ketanserin'; %actually lisuride 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data';
files(n).misc = '10 mg/kg'; 
files(n).tip1 = 750; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = []; 

n=n+1;
files(n).expt = '080916';
files(n).dir = '08_09_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_09_16_cluster_080916';
files(n).analysisfile = 'analysis_080916';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '10 mg/kg'; 
files(n).tip1 = 650; files(n).tip2 = 600; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = []; 


n=n+1;
files(n).expt = '080516';
files(n).dir = '08_05_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_05_16_cluster_080516';
files(n).analysisfile = 'analysis_080516';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '10 mg/kg'; 
files(n).tip1 = 750; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = []; %do not cluster sites 28,30,32,59,61,63 (used Johanna's probe (995F))

n=n+1;
files(n).expt = '072616';
files(n).dir = '07_26_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_26_16_cluster_072616';
files(n).analysisfile = 'analysis_072616';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'MGluR2'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '15mg/kg ly379268'; 
files(n).tip1 = 700; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = []; %do not cluster sites 28,30,32,59,61,63 (used Johanna's probe (995F))


n=n+1;
files(n).expt = '071616';
files(n).dir = '07_16_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_16_16_cluster_071616';
files(n).analysisfile = 'analysis_071616';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'MGluR2'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '15mg/kg ly379268'; 
files(n).tip1 = 700; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '071416';
files(n).dir = '07_14_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_14_16_cluster_071416';
files(n).analysisfile = 'analysis_071416';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'MGluR2'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '15mg/kg ly379268'; 
files(n).tip1 = 700; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '071116';
files(n).dir = '07_11_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_11_16_cluster_071116';
files(n).analysisfile = 'analysis_071116';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '15mg/kg ly379268'; 
files(n).tip1 = 700; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '060216';
files(n).dir = '06_02_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_06_02_16_cluster_060216';
files(n).analysisfile = 'analysis_060216';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post2';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = '';
files(n).postdrift = '';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post1';
files(n).pretreatment = 'ketanserin1';
files(n).injection = 'injection_doi';
files(n).treatment = 'KetanserinDOI';
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = 'dose: 15mg/kg ketanserin, 10mg/kg doi'; 
files(n).tip1 = 600; files(n).tip2 = 650; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';


% n=n+1;
% files(n).expt = '051216';
% files(n).dir = '05_12_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_12_16_cluster_051216';
% files(n).analysisfile = 'analysis_051216';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = 'dose: 10 mg/kg ketanserin 10mg/kg doi'; 
% files(n).tip1 = 550; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
% 
% n=n+1;
% files(n).expt = '051116';
% files(n).dir = '05_11_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_11_16_cluster_051116';
% files(n).analysisfile = 'analysis_051116';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = 'laser_pre_35'
% files(n).postpinpFile = 'laser_post_35'
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = ''; 
% files(n).tip1 = 550; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'wn_pre_051115_eye';  
% files(n).postdark_camera = 'wn_post_051116_eye';
% %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% n=n+1;
% files(n).expt = '050616';
% files(n).dir = '05_06_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_06_16_cluster_050616';
% files(n).analysisfile = 'analysis_050616';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1_test';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post_test';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'bad data'; %lost thresholds at the end, no running too
% files(n).misc = ''; 
% files(n).tip1 = 550; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% n=n+1;
% files(n).expt = '050416';
% files(n).dir = '05_04_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_04_16_cluster_050416';
% files(n).analysisfile = 'analysis_050416';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = 'bars_pre1';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi1';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = ''; 
% files(n).tip1 = 700; files(n).tip2 = 650; files(n).angle = 45;  %%% example
% files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% 
n=n+1;
files(n).expt = '042016';
files(n).dir = '04_20_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_20_16_cluster_042016';
files(n).analysisfile = 'analysis_042016';
files(n).predark = 'dark_pre1';
files(n).postdark = '';
files(n).prewn = 'wn_pre1';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = '';
files(n).prebars = 'bars_pre1';
files(n).postbars = '';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).prepinpFile = 'laser_pre_int_9_5'
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data';
files(n).misc = 'HTR2A_Pinp','lost units'; 
files(n).tip1 = 550; files(n).tip2 = 500; files(n).angle = 45;  %%% example
%files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example

% n=n+1;
% files(n).expt = '041516';
% files(n).dir = '04_15_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_04_15_16_cluster_041516';
% files(n).analysisfile = 'analysis_041516';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = 'drift_pre1';
% files(n).postdrift = 'drift_post1';
% files(n).prebars = 'bars_pre2';
% files(n).postbars = 'bars_post1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = 'ketanserin + DOI'; %animal seemed behaviorally on DOI, but no change in pupil
% files(n).tip1 = 550; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example

n=n+1;
files(n).expt = '041416';
files(n).dir = '04_14_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_14_16_cluster_041416';
files(n).analysisfile = 'analysis_041416';
files(n).predark = 'dark_pre1';
files(n).postdark = 'injection4';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post1';
files(n).injection = {'injection1' 'injection2' 'injection3'};
files(n).treatment = 'Ketanserin';
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = 'ketanserin ';
files(n).tip1 = 550; files(n).tip2 = 525; files(n).angle = 45;  %%% example
files(n).predark_camera = 'bars_pre_041416_eye';  
files(n).postdark_camera = 'bars_post_041416_eye';

n=n+1;
files(n).expt = '040716';
files(n).dir = '04_07_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_07_16_cluster_040716';
files(n).analysisfile = 'analysis_040716';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post3';
files(n).injection = 'injection';
files(n).treatment = 'DOI';
files(n).prepinpFile = ''
files(n).postpinpFile = 'laser_post_3_5'
files(n).layers = [];
files(n).notes = 'good data'; %%%% responsive??
files(n).misc = 'HTR2A_Pinp';
files(n).tip1 = 525; files(n).tip2 = 500; files(n).angle = 45;  %%% example
files(n).predark_camera = 'bars_pre_040716_eye';  
files(n).postdark_camera = 'bars_post_040716_eye';% 
files(n).badsites = [10 9];
% n=n+1;
% files(n).expt = '040616';
% files(n).dir = '04_06_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_04_06_16_cluster_040616';
% files(n).analysisfile = 'analysis_040616';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = 'bars_pre';
% files(n).postbars = 'bars_post';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = 'ketanserin + DOI';
% files(n).tip1 = 525; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% % %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example


n=n+1;
files(n).expt = '040116';
files(n).dir = '04_01_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_01_16_cluster_040116';
files(n).analysisfile = 'analysis_040116';
files(n).predark = 'dark_pre2';
files(n).postdark = 'dark_post';
files(n).prewn = 'wn_pre';
files(n).postwn = 'wn_post';  
files(n).predrift = '';
files(n).postdrift = '';
files(n).prebars = 'bars_pre';
files(n).postbars = 'bars_post';
files(n).injection = '';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = 'atropine';
files(n).tip1 = 525; files(n).tip2 = 500; files(n).angle = 45;  %%% example
files(n).badsites = [];

% %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% n=n+1;
% files(n).expt = '031716';
% files(n).dir = '03_17_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_03_17_16_cluster_031716';
% files(n).analysisfile = 'analysis_031716';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = '';  
% files(n).predrift = 'drift_pre1';
% files(n).postdrift = '';
% files(n).prebars = 'bars_pre1';
% files(n).postbars = '';
% files(n).injection = '';
% files(n).treatment = 'Saline';
% files(n).layers = [];
% files(n).notes = 'bad data' %testing new preamp...exceeded threshold, lost all units;
% files(n).misc = 'atropine';
% files(n).tip1 = 550; files(n).tip2 = 550; files(n).angle = 45;  %%% example
% %files(n).dark_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example

n=n+1;
files(n).expt = '030916';
files(n).dir = '03_09_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_03_09_16_cluster_030916';
files(n).analysisfile = 'analysis_030916';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post2';
files(n).injection = 'injection';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = 'atropine';
%files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  %%% example
files(n).predark_camera = 'bars_pre_030916_eye';  
files(n).postdark_camera = 'bars_post_030916_eye'; 
files(n).badsites = [ 14 12 10 9 7 6 2 ];
n=n+1;
files(n).expt = '020516';
files(n).dir = '02_05_16';
files(n).tank = '';
files(n).clusterfile = '';
files(n).analysisfile = '';
files(n).clusterfile = 'cluster_data_02_05_16_cluster_020516';
files(n).analysisfile = 'analysis_020516';
files(n).predark = 'dark_presal1';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal2';  
files(n).predrift = 'drift_presal1';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = 'bars_presal1';
files(n).postbars = 'bars_postsal2';
files(n).injection = 'injection';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).tip1 = 500; files(n).tip2 = 450; files(n).angle = 35;  %%% example
files(n).predark_camera = 'bars_presal_020516_eye';  
files(n).postdark_camera = 'bars_postsal_020516_eye';% 
files(n).badsites = [23 22 19 16 13 7 4 1];

n=n+1;
files(n).expt = '012916';
files(n).dir = '01_29_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_29_16_cluster_012916';
files(n).analysisfile = 'analysis_012916';
files(n).predark = 'dark_pre';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_pre';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_pre';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_pre2';
files(n).postbars = 'bars_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).predark_camera = 'bars_pre_012916_eye';  
files(n).postdark_camera = 'bars_postdoi_012916';
files(n).badsites = [ 41 38 37 26 25 23 21 20 19 17 15 14 13 12 4]; 
n=n+1;
files(n).expt = '010816';
files(n).dir = '01_08_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_08_16htr2a_doi_cluster_010816';
files(n).analysisfile = 'analysis_010816';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prepinpFile = 'laser_pre_int_075' %psth_power1
files(n).postpinpFile ='laser_postdoi_int075' %psth_power2
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'something happened during pre pinping - lost units';
files(n).misc = 'HTR2A_Pinp';


n=n+1;
files(n).expt = '010416';
files(n).dir = '01_04_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_04_16_cluster_010416';
files(n).analysisfile = 'analysis_010416';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi2';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [13 10 9 8 3 2 1];

n=n+1;
files(n).expt = '121415';
files(n).dir = '12_14_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_12_14_15_doi_cluster_121415';
files(n).analysisfile = 'analysis_121415';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [12 11 10 8 5];

n=n+1;
files(n).expt = '120915';
files(n).dir = '12_09_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_12_09_15_wtdoi_cluster_120915';
files(n).analysisfile = 'analysis_120915';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [4 5 6];
files(n).notes = 'bad data';
files(n).misc = 'seizure';
files(n).predark_camera = 'bars_predoi_120915';  
files(n).postdark_camera = 'bars_postdoi_120915';

n=n+1;
files(n).expt = '120415';
files(n).dir = '12_04_14';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_120415_cluster_120415';
files(n).analysisfile = 'analysis_120415';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = 'behavior';
files(n).badsites = [26 25 20 17 13 11 10 9 4];

n=n+1;
files(n).expt = '120215';
files(n).dir = '12_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_12_02_15_doi_cluster_120215';
files(n).analysisfile = 'analysis_120215';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).predark_camera = 'bars_predoi_120215';  
files(n).postdark_camera = 'bars_postdoi_120215'; 
files(n).badsites = [52 50 49 48 43 42 41 41 38 37 36 32 30 29 ...
                    27 26 21 20 19 18 17 16 14 13 11 10 9 8 6 5 4 3 2 1];

n=n+1;
files(n).expt = '111915';
files(n).dir = '11_19_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_11_19_15doi_cluster_111915';
files(n).analysisfile = 'analysis_111915';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_posdtdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'bad data';
files(n).misc = '';
files(n).predark_camera = 'bars_predoi_111915_eye';  
files(n).postdark_camera = 'bars_postdoi_111915_eye';

n=n+1;
files(n).expt = '110415';
files(n).dir = '11_04_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_11_04_15_DOI_cluster_110415';
files(n).analysisfile = 'analysis_110415';
files(n).predark = 'darkness_predoi3';
files(n).postdark = 'darkness_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [4 5 6];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [23 22 21 20 19 18];
% 
% n=n+1;
% files(n).expt = '102815';
% files(n).dir = '10_28_15';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_10_28_15_HTR2A_doi_cluster_102815';
% files(n).analysisfile = 'analysis_102815';
% files(n).predark = 'darrk_predoi1';
% files(n).postdark = 'dark_postdoi1';
% files(n).prewn = 'wn_predoi1';
% files(n).postwn = 'wn_postdoi1';
% files(n).predrift = 'drift_predoi1';
% files(n).postdrift = 'drift_postdoi1';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).prebackground = 'background_predoi1';
% files(n).postbackground = 'background_postdoi1';
% files(n).prepinpFile = 'laser_int4_5'
% files(n).postpinpFile = 'laser_int4_5_post'
% files(n).injection = 'injection';
% files(n).treatment = 'DOI';
% files(n).layers = [];
% files(n).notes = 'bad data';'no UDP';
% files(n).misc = 'HTR2A_Pinp';

n=n+1;
files(n).expt = '101915';
files(n).dir = '10_19_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_19_15_cluster_101915';
files(n).analysisfile = 'analysis_101915';
files(n).predark = 'dark_predoi2';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi2';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection';
files(n).treatment = 'DOI';
files(n).layers = [5 6];
files(n).notes = 'good data';
files(n).misc = ''; 32
files(n).badsites = [38 37 35 34 31 24 23 21 20 19 18 12 3];

n=n+1;
files(n).expt = '100915';
files(n).dir = '10_09_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_09_15_DOI_is_the_best';
files(n).analysisfile = 'analysis_100915';
files(n).predark = 'dark_presal1';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal1';
files(n).predrift = 'drift_presal1';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prebackground = 'background_presal1';
files(n).postbackground = 'background_postsal1';
files(n).injection = 'injection_1';
files(n).treatment = 'Saline';
files(n).layers = [5 6]; 
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [32 26 20 18 17 7 5 4];

n=n+1;
files(n).expt = '100215';
files(n).dir = '10_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_02_15_cluster_10_02_15';
files(n).analysisfile = 'analysis_100215';
files(n).predark = 'dark_presal3';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal1';
files(n).predrift = 'drift_presal1';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = 'bars_presal1';
files(n).postbars = 'bars_postsal1';
files(n).prebackground = 'background_presal1';
files(n).postbackground = 'background_postsal1';
files(n).injection = 'injection';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'units disappeared';
files(n).misc = '';
files(n).badsites = [7 ];

n=n+1;
files(n).expt = '093015';
files(n).dir = '09_30_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_30_15_cluster_093015';
files(n).analysisfile = 'analysis_093015';
files(n).predark = 'dark_predoi4';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drfit_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [44 40 27 20 19 18 14 13 11 10 7 6];

n=n+1;
files(n).expt = '092915';
files(n).dir = '09_29_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_29_15_cluster_092915';
files(n).analysisfile = 'analysis_092915';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).predark_camera = '09_29_15_bars_predoi_eye';  
files(n).postdark_camera = '09_29_15_bars_postdoi_eye'; 
files(n).badsites = [26 25 24 22 21 19 18 17 15];

n=n+1;
files(n).expt = '092315';
files(n).dir = '09_23_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_23_15_cluster_092315';
files(n).analysisfile = 'analysis_092315';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [20 19 18 17 16 10 9 2];
n=n+1;
files(n).expt = '092115';
files(n).dir = '09_21_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_21_15_cluster_092115';
files(n).analysisfile = 'analysis_092115';
files(n).predark = 'dark_presal1';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal1';
files(n).predrift = 'drift_presal';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = 'bars_presal1';
files(n).postbars = 'bars_postsal1';
files(n).prebackground = 'background_presal1';
files(n).postbackground = 'background_postsal1';
files(n).injection = 'inject_period';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'units all faded';
files(n).misc = '';
files(n).badsites = [19 18 16 15];

% n=n+1;
% files(n).expt = '091815';
% files(n).dir = '09_18_15';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_09_18_15_cluster_091815a';
% files(n).analysisfile = 'analysis_091815a';
% files(n).predark = 'dark_presal1';
% files(n).postdark = 'dark_postsal1';
% files(n).prewn = 'wn_presal1';
% files(n).postwn = 'wn_postsal1';
% files(n).predrift = 'drift_presal1';
% files(n).postdrift = 'drift_postsal1';
% files(n).prebars = 'bars_presal1';
% files(n).postbars = 'bars_postsal1';
% files(n).prebackground = 'background_presal1';
% files(n).postbackground = 'background_postsal1';
% files(n).injection = 'injection_period';
% files(n).treatment = 'Saline';
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = '';

% n=n+1;
% files(n).expt = '091415';
% files(n).dir = '09_14_15';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_09_14_15_cluster_09_14_15';
% files(n).analysisfile = 'analysis_091415';
% files(n).predark = 'dark_presal1';
% files(n).postdark = 'dark_postsaline1';
% files(n).prewn = 'wn_presal1';
% files(n).postwn = 'wn_postsal1';
% files(n).predrift = 'drift_presal1';
% files(n).postdrift = 'drift_postsaline1';
% files(n).prebars = 'bars_presal1';
% files(n).postbars = 'bars_postsaline1';
% files(n).prebackground = 'background_presal1';
% files(n).postbackground = 'background_postsaline';
% files(n).injection = 'injection_period';
% files(n).treatment = 'Saline';
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = '';

n=n+1;
files(n).expt = '090815';
files(n).dir = '09_08_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_08_15_cluster_090815';
files(n).analysisfile = 'analysis_090815';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift and changing threshold';
files(n).misc = '';
files(n).badsites = [42 41 38 35 33 32 29 28 26 25 24 22 19 18 17 16 13 12 11 ];


n=n+1;
files(n).expt = '090715';
files(n).dir = '09_07_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_07_15_cluster_090715';
files(n).analysisfile = 'analysis_090715';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'darkness_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift and high thresholds';
files(n).misc = '';
files(n).badsites = [ 40 39 38 37 36  34 33 32 29];
n=n+1;
files(n).expt = '090415';
files(n).dir = '09_04_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_04_15_cluster_090415';
files(n).analysisfile = 'analysis_090415';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [45 44 43 41 40 39 38];

n=n+1;
files(n).expt = '090215';
files(n).dir = '09_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_02_15_cluster_090215';
files(n).analysisfile = 'analysis_090215';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [36 34 33 32 31 30 29 28 27 26];

n=n+1;
files(n).expt = '083115';
files(n).dir = '08_31_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_31_15_cluster_083115';
files(n).analysisfile = 'analysis_083115';
files(n).predark = 'dark_prelis1';
files(n).postdark = 'dark_postlis1';
files(n).prewn = 'wn_prelis1';
files(n).postwn = 'wn_postlis1';
files(n).predrift = 'drift_prelis1';
files(n).postdrift = 'drift_postlis1';
files(n).prebars = 'bars_prelis1';
files(n).postbars = 'bars_postlis1';
files(n).prebackground = 'background_prelis1';
files(n).postbackground = 'background_postlis1';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [];

n=n+1;
files(n).expt = '082615';
files(n).dir = '08_26_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_26_15_cluster_082615';
files(n).analysisfile = 'analysis_082615';
files(n).predark = 'dark_prelis1';
files(n).postdark = 'dark_postlis1';
files(n).prewn = 'wn_prelis1';
files(n).postwn = 'wn_postlis1';
files(n).predrift = 'drift_prelis1';
files(n).postdrift = 'drift_postlis1';
files(n).prebars = 'bars_prelis1';
files(n).postbars = 'bars_postlis1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';

n=n+1;
files(n).expt = '082515';
files(n).dir = '08_25_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_25_15_clust';
files(n).analysisfile = 'analysis_082515';
files(n).predark = 'dark_prelis1';
files(n).postdark = 'dark_poslis1';
files(n).prewn = 'wn_prelis1';
files(n).postwn = 'wn_postlis1';
files(n).predrift = 'drift_prelis1';
files(n).postdrift = 'drift_poslis1';
files(n).prebars = 'bars_prelis1';
files(n).postbars = 'bars_postlis1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';

n=n+1;
files(n).expt = '082115';
files(n).dir = '08_21_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_21_15_cluster_082115';
files(n).analysisfile = 'analysis_082115';
files(n).predark = 'dark_presaline1';
files(n).postdark = 'dark_postsaline1';
files(n).prewn = 'wn_presaline1';
files(n).postwn = 'wn_postsaline1';
files(n).predrift = 'drift_presaline1';
files(n).postdrift = 'drift_postsaline1';
files(n).prebars = 'bars_presaline1';
files(n).postbars = 'bars_postsaline1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'something shift during first drift. maybe redo from wn on? also clipped units';
files(n).misc = '';
files(n).badsites = [30 27 26 24 23 22 21 20 19 15 14 13 12]
% 
n=n+1;
files(n).expt = '081915';
files(n).dir = '08_19_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_19_15_cluster_081815';
files(n).analysisfile = 'analysis_081915';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [ 22 21];

n=n+1;
files(n).expt = '081315';
files(n).dir = '08_13_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_13_15_cluster_081315a';
files(n).analysisfile = 'analysis_081315a';
files(n).predark = 'dark_pre_lisuride1';
files(n).postdark = 'dark_post_lisuride1';
files(n).prewn = 'wn_pre_lisuride1';
files(n).postwn = 'wn_post_lisuride1';
files(n).predrift = 'drift_pre_lisuride1';
files(n).postdrift = 'drift_post_lisuride1';
files(n).prebars = 'bars_pre_lisuride1';
files(n).postbars = 'bars_post_lisuride1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';

n=n+1;
files(n).expt = '081215';
files(n).dir = '08_12_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_12_15_cluster_081215';
files(n).analysisfile = 'analysis_081215';
files(n).predark = 'dark_pre_saline1';
files(n).postdark = 'dark_post_saline1';
files(n).prewn = 'wn_pre_saline1';
files(n).postwn = 'wn_post_saline1';
files(n).predrift = 'drift_pre_saline1';
files(n).postdrift = 'drift_post_saline1';
files(n).prebars = 'bars_pre_saline1';
files(n).postbars = 'bars_post_saline1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'redo select units';
files(n).misc = '';
files(n).badsites = [40 39 38 37 36 35 33 29 27 22];

n=n+1;
files(n).expt = '080715';
files(n).dir = '08_07_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_07_15_cluster_080715';
files(n).analysisfile = 'analysis_080715';
files(n).predark = 'dark_pre_doi1';
files(n).postdark = 'dark_post_doi1';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_post_doi1';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [27 25 24 23 21 20 19 18 17 15 14 12 10 9 7 5 3 1];

n=n+1;
files(n).expt = '080515';
files(n).dir = '08_05_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_05_15_cluster_080515';
files(n).analysisfile = 'analysis_080515';
files(n).predark = 'dark_pre_doi_2';
files(n).postdark = 'dark_post_doi_2';
files(n).prewn = 'wn_pre_doi_2';
files(n).postwn = 'wn_post_doi_2';
files(n).predrift = 'drift_pre_doi2';
files(n).postdrift = 'drift_post_doi2';
files(n).prebars = 'bars_pre_doi2';
files(n).postbars = 'bars_post_doi2';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period2';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [ 6 2]

n=n+1;
files(n).expt = '080315';
files(n).dir = '08_03_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_03_15_cluster_080315';
files(n).analysisfile = 'analysis_080315';
files(n).predark = 'dark_pre_doi1';
files(n).postdark = 'dark_post_doi1';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_post_doi2';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';

n=n+1;
files(n).expt = '080215';
files(n).dir = '08_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_02_15_cluster_080215';
files(n).analysisfile = 'analysis_080215';
files(n).predark = 'dark_pre_doi2';
files(n).postdark = 'darkness_post_doi1';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period2';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [23 22 21 20 15 14 12 10 9 8 7 5 4 3];
n=n+1;
files(n).expt = '072915';
files(n).dir = '7_29_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_29_15_cluster_072915';
files(n).analysisfile = 'analysis_072915';
files(n).predark = 'dark_pre_doi1';
files(n).postdark = 'dark_post_injection2';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_post_doi1';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [26 25 24 22 18 17 16 15 14 13 12 11 10];

n=n+1;
files(n).expt = '072515';
files(n).dir = '7_25_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_25_15_cluster_data';
files(n).analysisfile = 'analysis_file';
files(n).predark = 'dark_pre_doi_rec1';
files(n).postdark = 'dark_post_doi_7 min';
files(n).prewn = 'wn_pre_doi_rec1';
files(n).postwn = 'wn_post_doi_rec1';
files(n).predrift = 'drift_pre_doi_rec1';
files(n).postdrift = 'drift_post_doi_rec1';
files(n).prebars = 'bars_pre_doi_rec1';
files(n).postbars = 'bars_post_doi_rec1';
files(n).injection = 'injectionperiod';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [7 6 5 1];
% n=n+1;
% files(n).expt = '7_23_15';
% files(n).dir = '7_23_15_recluster';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_07_23_15_cluster_data';
% files(n).analysisfile = 'analysis_07_23_15';
% files(n).predark = 'dark_predoi_rec1';
% files(n).postdark = 'dark_post_doi_rec2';
% files(n).prewn = 'wnmovie_pre_doi_rec1';
% files(n).postwn = 'wnmovie_post_doi_rec1';
% files(n).predrift = 'drift_pre_doi_rec1';
% files(n).postdrift = 'drift_post_doi_rec1';
% files(n).prebars = 'bars_pre_doi_rec1';
% files(n).postbars = 'bars_post_doi_rec1';
% files(n).injection = '';
% files(n).treatment = 'DOI';
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = '';

% n=n+1;
% files(n).expt = '7_16_15';
% files(n).dir = '7_16_15';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_07_16_15_07_16_15_etohcontrol_cluster_data';
% files(n).analysisfile = 'analysis_etoh_control';
% files(n).predark = 'dark_before_rec1';
% files(n).postdark = 'dark_post_injection_rec2_7min';
% files(n).prewn = 'wnmovie_before_rec1';
% files(n).postwn = 'wnmovie_post_injection_rec1';
% files(n).predrift = 'drift_before_rec1';
% files(n).postdrift = 'drift_post_injection_rec1';
% files(n).prebars = 'bars_baseline_rec1';
% files(n).postbars = 'bars_post_injection_rec2';
% files(n).injection = '';
% files(n).treatment = 'EtOH';
% files(n).layers = [];
% files(n).notes = 'good data';



for f = 1:length(files);
    files(f).blockWn = {files(f).prewn files(f).postwn};
    files(f).blockDark = {files(f).predark files(f).postdark};
    files(f).blockBar = {files(f).prebars files(f).postbars};
    files(f).blockDrift = {files(f).predrift files(f).postdrift};
end


