pathname = '\\angie\Angie_analysis\DOI_experiments';
n=0;


n=n+1;
files(n).expt = '011817';
files(n).dir = '01_18_17';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_18_17_cluster_011817';
files(n).analysisfile = 'analysis_011817';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dar_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre3';
files(n).postdrift = 'drift_post1';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
% files(n).layers(1:10) = 2; (11:?
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 90;%vertical penetration 
files(n).badsites = [];


n=n+1;
files(n).expt = '011117';
files(n).dir = '01_11_17';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_11_17_cluster_011117';
files(n).analysisfile = 'analysis_011117';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).predetect = 'detection-pre1';
files(n).postdetect = 'detection_post2';
files(n).prebars = ''; 
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
% files(n).layers(1:10) = 2; (11:?
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 90;%vertical penetration 
files(n).badsites = [];


n=n+1;
files(n).expt = '010917';
files(n).dir = '01_09_17';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_09_17_cluster_010917';
files(n).analysisfile = 'analysis_010917';
files(n).predark = 'dark_pre2';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = '';
files(n).postdrift = '';
files(n).prebars = ''; 
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
% files(n).layers(1:10) = 2; (11:?
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 600; files(n).tip2 = 600; files(n).angle = 45;
files(n).badsites = [3 8 10 20];


n=n+1;
files(n).expt = '112116';
files(n).dir = '11_21_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_11_21_16_cluster_112116';
files(n).analysisfile = 'analysis_112116';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = 'bars_pre1'; %not clustered
files(n).postbars = 'bars_post1'; %not clustered
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
% files(n).layers(1:10) = 2; (11:?
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 90;%vertical penetration 
files(n).badsites = [1 4 5 11 12 18];


n=n+1;
files(n).expt = '110416';
files(n).dir = '11_04_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_11_04_16_cluster_110416';
files(n).analysisfile = 'analysis_110416b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 575; files(n).tip2 = 575; files(n).angle = 45;  
files(n).badsites = [];


n=n+1;
files(n).expt = '110316';
files(n).dir = '11_03_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_11_03_16_cluster_110316';
files(n).analysisfile = 'analysis_110316b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];



n=n+1;
files(n).expt = '102716';
files(n).dir = '10_27_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_27_16_cluster_102716';
files(n).analysisfile = 'analysis_102716b'; 
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post2';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; %only a few units
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '102516';
files(n).dir = '10_25_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_25_16_cluster_102516';
files(n).analysisfile = 'analysis_102516';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; %drift
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '102116';
files(n).dir = '10_21_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_21_16_cluster_102116';
files(n).analysisfile = 'analysis_102116b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre2';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = '';
files(n).layers = [];
files(n).notes = 'good data'; %only 3 units...last dark block very quiet...drift?
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = []; %[8 13 14];

n=n+1;
files(n).expt = '102016';
files(n).dir = '10_20_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_20_16_cluster_102016';
files(n).analysisfile = 'analysis_102016b'; %reselected
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '101316';
files(n).dir = '10_13_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_13_16_cluster_101316';
files(n).analysisfile = 'analysis_101316b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline';  
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 540; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '101216';
files(n).dir = '10_12_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_12_16_cluster_101216';
files(n).analysisfile = 'analysis_101216b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI';  
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; %bad thresholds only one good unit
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 475; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '101116';
files(n).dir = '10_11_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_11_16_cluster_101116';
files(n).analysisfile = 'analysis_101116b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'inection';
files(n).treatment = 'Saline';  
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '100716';
files(n).dir = '10_07_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_07_16_cluster_100716';
files(n).analysisfile = 'analysis_100716b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '100616';
files(n).dir = '10_06_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_06_16_cluster_100616';
files(n).analysisfile = 'analysis_100616';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI'; %5mg/kg
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; % some drift...I don't trust this data
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 475; files(n).angle = 35;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '100416';
files(n).dir = '10_04_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_04_16_cluster_100416';
files(n).analysisfile = 'analysis_100416b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '093016';
files(n).dir = '09_30_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_30_16_cluster_093016';
files(n).analysisfile = 'analysis_093016b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '092916';
files(n).dir = '09_29_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_29_16_cluster_092916';
files(n).analysisfile = 'analysis_092916';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = '';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; %only one unit...don't trust this dataset
files(n).misc = ''; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45; 
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];



n=n+1;
files(n).expt = '092716';
files(n).dir = '09_27_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_27_16_cluster_092716';
files(n).analysisfile = 'analysis_092716b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 550; files(n).tip2 = 580; files(n).angle = 45;  %%% example
% files(n).predark_camera = '';  
% files(n).postdark_camera = '';
files(n).badsites = [];


n=n+1;
files(n).expt = '092616';
files(n).dir = '09_26_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_26_16_cluster_092616';
files(n).analysisfile = 'analysis_092616';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; 
files(n).misc = ''; 
files(n).tip1 = 600; files(n).tip2 = 600; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '092116';
files(n).dir = '09_21_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_21_16_cluster_092116';
files(n).analysisfile = 'analysis_092116b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = '5HT'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 615; files(n).tip2 = 625; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [2 6 7]; %these look good except drift_pre has very low activity, like activity drifted in



n=n+1;
files(n).expt = '091516';
files(n).dir = '09_15_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_15_16_cluster_091516';
files(n).analysisfile = 'analysis_091516';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'poor vis resp';  %%% marked by cmn 103116 
files(n).misc = ''; 
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 35; 
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [3 4 5];



n=n+1;
files(n).expt = '091216';
files(n).dir = '09_12_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_12_16_cluster_091216';
files(n).analysisfile = 'analysis_091216';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; %few units, not very stable
files(n).misc = ''; 
files(n).tip1 = 550; files(n).tip2 = 550; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [2 3 7 8];


n=n+1;
files(n).expt = '090916';
files(n).dir = '09_09_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_09_16_cluster_090916';
files(n).analysisfile = 'analysis_090916b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = ''; 
files(n).tip1 = 600; files(n).tip2 = 600; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];



n=n+1;
files(n).expt = '090816';
files(n).dir = '09_08_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_08_16_cluster_090816';
files(n).analysisfile = 'analysis_090816b'; %re-selected
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; 
files(n).misc = ''; 
files(n).tip1 = 750; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '090716';
files(n).dir = '09_07_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_07_16_cluster_090716';
files(n).analysisfile = 'analysis_090716';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post2';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre2';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; 
files(n).misc = ''; 
% files(n).predark_camera = 'dark_pre_090116_eye';  
% files(n).postdark_camera = 'dark_post_090116_eye';
files(n).badsites = [1 6];
files(n).tip1 = 750; files(n).tip2 = 750; files(n).angle = 45;


% n=n+1;
% files(n).expt = '090616';
% files(n).dir = '09_06_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_09_06_16_cluster_090616';
% files(n).analysisfile = 'analysis_090616_quiet';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = 'drift_pre1';
% files(n).postdrift = 'drift_post1';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = '';
% files(n).injection = 'injection';
% files(n).treatment = 'Lisuride'; 
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = ''; 
% files(n).tip1 = 750; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% % files(n).predark_camera = 'dark_pre_090116_eye';  
% % files(n).postdark_camera = 'dark_post_090116_eye';
% files(n).badsites = [];

%compile stopped here, but still good data
% n=n+1;
% files(n).expt = '090116';
% files(n).dir = '09_01_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_09_01_16_cluster_090116';
% files(n).analysisfile = 'analysis_090116';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = 'drift_pre1';
% files(n).postdrift = 'drift_post1';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = 'injection_mglur2';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'MGluR2DOI'; 
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = ''; 
% files(n).tip1 = 750; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% % files(n).predark_camera = 'dark_pre_090116_eye';  
% % files(n).postdark_camera = 'dark_post_090116_eye';
% files(n).badsites = [];


% n=n+1;
% files(n).expt = '083016';
% files(n).dir = '08_30_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_08_30_16_cluster_083016';
% files(n).analysisfile = 'analysis_083016';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = 'drift_pre1';
% files(n).postdrift = 'drift_post1';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = '';
% files(n).injection = 'injection';
% files(n).treatment = 'DOI'; 
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = 'Behavior Mouse'; 
% files(n).tip1 = 750; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% % files(n).predark_camera = 'dark_pre_051216_eye';  
% % files(n).postdark_camera = 'dark_post_051216_eye';
% files(n).badsites = [];


n=n+1;
files(n).expt = '082616';
files(n).dir = '08_26_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_26_16_cluster_082616';
files(n).analysisfile = 'analysis_082616b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';% compile getting stuck here on STAs
files(n).postwn = 'wn_post1';% compile getting stuck here 
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; %re-selected units
files(n).misc = ''; 
files(n).tip1 = 750; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '082416';
files(n).dir = '08_24_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_24_16_cluster_082416';
files(n).analysisfile = 'analysis_082416b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; %re-selected
files(n).misc = ''; 
files(n).tip1 = 650; files(n).tip2 = 600; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '081716';
files(n).dir = '08_17_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_17_16_cluster_081816';
files(n).analysisfile = 'analysis_081716';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = 'injection_mglur2';
files(n).injection = 'injection_doi';
files(n).treatment = 'MGluR2DOI';
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '15 mg/kg ly37... _ 10 mg/kg DOI'; 
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 50;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '081516';
files(n).dir = '08_15_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_15_16_cluster_081516';
files(n).analysisfile = 'analysis_081516b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = 'Lisuride'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '4 mg/kg'; 
files(n).tip1 = 600; files(n).tip2 = 650; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '081216';
files(n).dir = '08_12_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_12_16_cluster_081216';
files(n).analysisfile = 'analysis_081216a';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; %re-seleced, but only one good unit...tried a second time...too much drift
files(n).misc = '10 mg/kg'; 
files(n).tip1 = 700; files(n).tip2 = 725; files(n).angle = 45; 
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

%Ian's recording
n=n+1;
files(n).expt = '081116';
files(n).dir = '08_11_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_11_16_cluster_081116';
files(n).analysisfile = 'analysis_081116b'; %re-selected
files(n).predark = 'darkness_pre02';
files(n).postdark = 'darkness_post02';
files(n).prewn = '';% 'wn_pre01'; stopping in compile for STAs
files(n).postwn = '';% 'wn_post01';  
files(n).predrift = 'gratings_pre01';
files(n).postdrift = 'gratings_post01';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection_bars';
files(n).treatment = 'Lisuride'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; %Ian did recording 
files(n).misc = '4 mg/kg'; 
files(n).tip1 = 575; files(n).tip2 = 600; files(n).angle = 40;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];


n=n+1;
files(n).expt = '081016';
files(n).dir = '08_10_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_10_16_cluster_081016';
files(n).analysisfile = 'analysis_081016';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn _pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Ketanserin'; %actually lisuride 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data';
files(n).misc = '10 mg/kg'; 
files(n).tip1 = 675; files(n).tip2 = 675; files(n).angle = 35;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = []; 

n=n+1;
files(n).expt = '080916';
files(n).dir = '08_09_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_09_16_cluster_080916';
files(n).analysisfile = 'analysis_080916b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; %re-selected units
files(n).misc = ''; 
files(n).tip1 = 600; files(n).tip2 = 600; files(n).angle = 35;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = []; 


n=n+1;
files(n).expt = '080516';
files(n).dir = '08_05_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_05_16_cluster_080516';
files(n).analysisfile = 'analysis_080516';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'Saline'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'poor vis resp';   %%% noted by cmn 102616, not vis resp
files(n).misc = '10 mg/kg'; 
files(n).tip1 = 600; files(n).tip2 = 600; files(n).angle = 35;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [4 6 10]; %do not cluster sites 28,30,32,59,61,63 (used Johanna's probe (995F))

n=n+1;
files(n).expt = '072616';
files(n).dir = '07_26_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_26_16_cluster_072616';
files(n).analysisfile = 'analysis_072616';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'MGluR2'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '15mg/kg ly379268'; 
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = []; %do not cluster sites 28,30,32,59,61,63 (used Johanna's probe (995F))


n=n+1;
files(n).expt = '071616';
files(n).dir = '07_16_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_16_16_cluster_071616';
files(n).analysisfile = 'analysis_071616b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'MGluR2'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data'; %when re-selected
files(n).misc = '15mg/kg ly379268'; 
files(n).tip1 = 700; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '071416';
files(n).dir = '07_14_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_14_16_cluster_071416';
files(n).analysisfile = 'analysis_071416b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'MGluR2'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '15mg/kg ly379268'; 
files(n).tip1 = 700; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [];

n=n+1;
files(n).expt = '071116';
files(n).dir = '07_11_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_11_16_cluster_071116';
files(n).analysisfile = 'analysis_071116b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = '';
files(n).postbars = '';
files(n).pretreatment = '';
files(n).injection = 'injection';
files(n).treatment = 'DOI'; 
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data'; %re-selected, many units
files(n).misc = ''; 
files(n).tip1 = 700; files(n).tip2 = 750; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
files(n).badsites = [2];


n=n+1;
files(n).expt = '060216';
files(n).dir = '06_02_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_06_02_16_cluster_060216';
files(n).analysisfile = 'analysis_060216b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post2';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = '';
files(n).postdrift = '';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post1';
files(n).pretreatment = 'ketanserin1';
files(n).injection = 'injection_doi';
files(n).treatment = 'KetanserinDOI';
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = 'dose: 15mg/kg ketanserin, 10mg/kg doi'; 
files(n).tip1 = 600; files(n).tip2 = 650; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';


% n=n+1;
% files(n).expt = '051216';
% files(n).dir = '05_12_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_12_16_cluster_051216';
% files(n).analysisfile = 'analysis_051216';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = 'dose: 10 mg/kg ketanserin 10mg/kg doi'; 
% files(n).tip1 = 550; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'dark_pre_051216_eye';  
% files(n).postdark_camera = 'dark_post_051216_eye';
% 
% n=n+1;
% files(n).expt = '051116';
% files(n).dir = '05_11_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_11_16_cluster_051116';
% files(n).analysisfile = 'analysis_051116';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = 'laser_pre_35'
% files(n).postpinpFile = 'laser_post_35'
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = ''; 
% files(n).tip1 = 550; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).predark_camera = 'wn_pre_051115_eye';  
% files(n).postdark_camera = 'wn_post_051116_eye';
% %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% n=n+1;
% files(n).expt = '050616';
% files(n).dir = '05_06_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_06_16_cluster_050616';
% files(n).analysisfile = 'analysis_050616';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1_test';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post_test';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'bad data'; %lost thresholds at the end, no running too
% files(n).misc = ''; 
% files(n).tip1 = 550; files(n).tip2 = 700; files(n).angle = 45;  %%% example
% files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% n=n+1;
% files(n).expt = '050416';
% files(n).dir = '05_04_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_05_04_16_cluster_050416';
% files(n).analysisfile = 'analysis_050416';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = 'bars_pre1';
% files(n).postbars = '';
% files(n).pretreatment = 'ketanserin1';
% files(n).injection = 'injection_doi1';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = ''; 
% files(n).tip1 = 700; files(n).tip2 = 650; files(n).angle = 45;  %%% example
% files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% 
n=n+1;
files(n).expt = '042016';
files(n).dir = '04_20_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_20_16_cluster_042016';
files(n).analysisfile = 'analysis_042016';
files(n).predark = 'dark_pre1';
files(n).postdark = '';
files(n).prewn = 'wn_pre1';
files(n).postwn = '';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = '';
files(n).prebars = 'bars_pre1';
files(n).postbars = '';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).prepinpFile = 'laser_pre_int_9_5'
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'bad data';
files(n).misc = 'HTR2A_Pinp','lost units'; 
files(n).tip1 = 550; files(n).tip2 = 500; files(n).angle = 45;  %%% example
%files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example

% n=n+1; OLD DOSE
% files(n).expt = '041516';
% files(n).dir = '04_15_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_04_15_16_cluster_041516';
% files(n).analysisfile = 'analysis_041516';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = 'drift_pre1';
% files(n).postdrift = 'drift_post1';
% files(n).prebars = 'bars_pre2';
% files(n).postbars = 'bars_post1';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).prepinpFile = ''
% files(n).postpinpFile = ''
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = 'ketanserin + DOI'; %animal seemed behaviorally on DOI, but no change in pupil
% files(n).tip1 = 550; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example



n=n+1;
files(n).expt = '041416';
files(n).dir = '04_14_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_14_16_cluster_041416';
files(n).analysisfile = 'analysis_041416b';
files(n).predark = 'dark_pre1';
files(n).postdark = 'injection4';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post1';
files(n).injection = {'injection1' 'injection2' 'injection3'};
files(n).treatment = 'Ketanserin';
files(n).prepinpFile = ''
files(n).postpinpFile = ''
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = 'ketanserin ';
files(n).tip1 = 550; files(n).tip2 = 525; files(n).angle = 45;  %%% example
files(n).predark_camera = 'bars_pre_041416_eye';  
files(n).postdark_camera = 'bars_post_041416_eye';

n=n+1;
files(n).expt = '040716';
files(n).dir = '04_07_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_07_16_cluster_040716';
files(n).analysisfile = 'analysis_040716';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post3';
files(n).injection = 'injection';
files(n).treatment = 'DOI';
files(n).prepinpFile = ''
files(n).postpinpFile = 'laser_post_3_5'
files(n).layers = [];
files(n).notes = 'bad data'; %re-selected...no good units %%%% responsive??
files(n).misc = 'HTR2A_Pinp';
files(n).tip1 = 525; files(n).tip2 = 500; files(n).angle = 45;  %%% example
files(n).predark_camera = 'bars_pre_040716_eye';  
files(n).postdark_camera = 'bars_post_040716_eye';% 
files(n).badsites = [10 9];
% n=n+1;
% files(n).expt = '040616';
% files(n).dir = '04_06_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_04_06_16_cluster_040616';
% files(n).analysisfile = 'analysis_040616';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = 'wn_post1';  
% files(n).predrift = '';
% files(n).postdrift = '';
% files(n).prebars = 'bars_pre';
% files(n).postbars = 'bars_post';
% files(n).injection = 'injection_doi';
% files(n).treatment = 'KetanserinDOI';
% files(n).layers = [];
% files(n).notes = 'good data';
% files(n).misc = 'ketanserin + DOI';
% files(n).tip1 = 525; files(n).tip2 = 500; files(n).angle = 45;  %%% example
% % %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example


n=n+1;
files(n).expt = '040116';
files(n).dir = '04_01_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_04_01_16_cluster_040116';
files(n).analysisfile = 'analysis_040116';
files(n).predark = 'dark_pre2';
files(n).postdark = 'dark_post';
files(n).prewn = 'wn_pre';
files(n).postwn = 'wn_post';  
files(n).predrift = '';
files(n).postdrift = '';
files(n).prebars = 'bars_pre';
files(n).postbars = 'bars_post';
files(n).injection = '';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'drift'; %re-selected, no good units
files(n).misc = 'atropine';
files(n).tip1 = 525; files(n).tip2 = 500; files(n).angle = 45;  %%% example
files(n).badsites = [];

% %files(n).wn_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example
% 
% n=n+1;
% files(n).expt = '031716';
% files(n).dir = '03_17_16';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_03_17_16_cluster_031716';
% files(n).analysisfile = 'analysis_031716';
% files(n).predark = 'dark_pre1';
% files(n).postdark = 'dark_post1';
% files(n).prewn = 'wn_pre1';
% files(n).postwn = '';  
% files(n).predrift = 'drift_pre1';
% files(n).postdrift = '';
% files(n).prebars = 'bars_pre1';
% files(n).postbars = '';
% files(n).injection = '';
% files(n).treatment = 'Saline';
% files(n).layers = [];
% files(n).notes = 'bad data' %testing new preamp...exceeded threshold, lost all units;
% files(n).misc = 'atropine';
% files(n).tip1 = 550; files(n).tip2 = 550; files(n).angle = 45;  %%% example
% %files(n).dark_camera = {'eyefile1.mat','eyefile2.mat'};  %%% example

n=n+1;
files(n).expt = '030916';
files(n).dir = '03_09_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_03_09_16_cluster_030916';
files(n).analysisfile = 'analysis_030916a';
files(n).predark = 'dark_pre1';
files(n).postdark = 'dark_post1';
files(n).prewn = 'wn_pre1';
files(n).postwn = 'wn_post1';  
files(n).predrift = 'drift_pre1';
files(n).postdrift = 'drift_post1';
files(n).prebars = 'bars_pre1';
files(n).postbars = 'bars_post2';
files(n).injection = 'injection';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'bad data'; %HTR2A animal...use data? only one good unit
files(n).misc = 'atropine';
%files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  %%% example
files(n).predark_camera = 'bars_pre_030916_eye';  
files(n).postdark_camera = 'bars_post_030916_eye'; 
files(n).badsites = [ 14 12 10 9 7 6 2 ];
%Laser trials

n=n+1;
files(n).expt = '020516';
files(n).dir = '02_05_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_02_05_16_cluster_020516';
files(n).analysisfile = 'analysis_020516b';
files(n).predark = 'dark_presal1';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal2';  
files(n).predrift = 'drift_presal1';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = 'bars_presal1';
files(n).postbars = 'bars_postsal2';
files(n).injection = 'injection';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'good data';% not great data %re-selected, could get more units by cutting out dark pre (much lower than dark post)
files(n).misc = '';
files(n).tip1 = 500; files(n).tip2 = 450; files(n).angle = 35;  
files(n).predark_camera = 'bars_presal_020516_eye';  
files(n).postdark_camera = 'bars_postsal_020516_eye';% 
files(n).badsites =[1 2 3 4 5];% bad sites with old analysis file: [23 22 19 16 13 7 4 1];

n=n+1;
files(n).expt = '012916';
files(n).dir = '01_29_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_29_16_cluster_012916';
files(n).analysisfile = 'analysis_012916b';
files(n).predark = 'dark_pre';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_pre';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_pre';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_pre2';
files(n).postbars = 'bars_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).predark_camera = 'bars_pre_012916_eye';  
files(n).postdark_camera = 'bars_postdoi_012916';
files(n).tip1 = 600; files(n).tip2 = 550; files(n).angle = 45;  
files(n).badsites = []; %re-seleced bad sites from old analysis file: [ 41 38 37 26 25 23 21 20 19 17 15 14 13 12 4]; 

n=n+1;
files(n).expt = '010816';
files(n).dir = '01_08_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_08_16htr2a_doi_cluster_010816';
files(n).analysisfile = 'analysis_010816';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prepinpFile = 'laser_pre_int_075' %psth_power1
files(n).postpinpFile ='laser_postdoi_int075' %psth_power2
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'something happened during pre pinping - lost units';
files(n).misc = 'HTR2A_Pinp';


n=n+1;
files(n).expt = '010416';
files(n).dir = '01_04_16';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_01_04_16_cluster_010416';
files(n).analysisfile = 'analysis_010416b';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi2';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
%files(n).layersites = (1:16)=5;(17:32)=6;(33:49)=5;(40:64)=6
files(n).notes = 'good data'; %re-seleced
files(n).tip1 = 600; files(n).tip2 = 550; files(n).angle = 45;  
files(n).misc = '';
files(n).badsites = [];

n=n+1;
files(n).expt = '121415';
files(n).dir = '12_14_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_12_14_15_doi_cluster_121415';
files(n).analysisfile = 'analysis_121415';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift'; %tried to re-select units,bad data
files(n).misc = '';
files(n).badsites = [12 11 10 8 5];

n=n+1;
files(n).expt = '120915';
files(n).dir = '12_09_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_12_09_15_wtdoi_cluster_120915';
files(n).analysisfile = 'analysis_120915';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [4 5 6];
files(n).notes = 'bad data';
files(n).misc = 'seizure';
files(n).predark_camera = 'bars_predoi_120915';  
files(n).postdark_camera = 'bars_postdoi_120915';

n=n+1;
files(n).expt = '120415';
files(n).dir = '12_04_14';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_120415_cluster_120415';
files(n).analysisfile = 'analysis_120415';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'behavior'; % good data';
files(n).misc = 'behavior';
files(n).badsites = [26 25 20 17 13 11 10 9 4];

n=n+1;
files(n).expt = '120215';
files(n).dir = '12_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_12_02_15_doi_cluster_120215';
files(n).analysisfile = 'analysis_120215';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'large shift'; %re-selected, all bad unis %%% modified by cmn 092116 
files(n).misc = '';
files(n).predark_camera = 'bars_predoi_120215';  
files(n).postdark_camera = 'bars_postdoi_120215'; 
files(n).badsites = [52 50 49 48 43 42 41 41 38 37 36 32 30 29 ...
                    27 26 21 20 19 18 17 16 14 13 11 10 9 8 6 5 4 3 2 1];
files(n).tip1 = 700; files(n).tip2 = 650; files(n).angle = 45;  


n=n+1;
files(n).expt = '111915';
files(n).dir = '11_19_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_11_19_15doi_cluster_111915';
files(n).analysisfile = 'analysis_111915';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_posdtdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'bad data'; %not sure why bad data...if desperae re-select
files(n).misc = '';
files(n).predark_camera = 'bars_predoi_111915_eye';  
files(n).postdark_camera = 'bars_postdoi_111915_eye';
files(n).tip1 = 675; files(n).tip2 = 625; files(n).angle = 45;  


n=n+1;
files(n).expt = '110415';
files(n).dir = '11_04_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_11_04_15_DOI_cluster_110415';
files(n).analysisfile = 'analysis_110415';
files(n).predark = 'darkness_predoi3';
files(n).postdark = 'darkness_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [4 5 6];
files(n).notes = 'drift';%tried to re-select, very noisy
files(n).misc = '';
files(n).badsites = [23 22 21 20 19 18];
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  

% 
% n=n+1;
% files(n).expt = '102815';
% files(n).dir = '10_28_15';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_10_28_15_HTR2A_doi_cluster_102815';
% files(n).analysisfile = 'analysis_102815';
% files(n).predark = 'darrk_predoi1';
% files(n).postdark = 'dark_postdoi1';
% files(n).prewn = 'wn_predoi1';
% files(n).postwn = 'wn_postdoi1';
% files(n).predrift = 'drift_predoi1';
% files(n).postdrift = 'drift_postdoi1';
% files(n).prebars = '';
% files(n).postbars = '';
% files(n).prebackground = 'background_predoi1';
% files(n).postbackground = 'background_postdoi1';
% files(n).prepinpFile = 'laser_int4_5'
% files(n).postpinpFile = 'laser_int4_5_post'
% files(n).injection = 'injection';
% files(n).treatment = 'DOI';
% files(n).layers = [];
% files(n).notes = 'bad data';'no UDP';
% files(n).misc = 'HTR2A_Pinp';

n=n+1;
files(n).expt = '101915';
files(n).dir = '10_19_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_19_15_cluster_101915';
files(n).analysisfile = 'analysis_101915b';
files(n).predark = 'dark_predoi2';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi2';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection';
files(n).treatment = 'DOI';
files(n).layers = [5 6];
files(n).notes = 'good data' %%% lots of bad sites and weak vis resp, marked by cmn 103116
files(n).misc = ''; %32
files(n).badsites = [1 2 3 5 6 13]%[38 37 35 34 31 24 23 21 20 19 18 12 3];
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45; %make sure this matches with original analysis file

n=n+1;
files(n).expt = '100915';
files(n).dir = '10_09_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_09_15_DOI_is_the_best';
files(n).analysisfile = 'analysis_100915';
files(n).predark = 'dark_presal1';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal1';
files(n).predrift = 'drift_presal1';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = '';
files(n).postbars = '';
files(n).prebackground = 'background_presal1';
files(n).postbackground = 'background_postsal1';
files(n).injection = 'injection_1';
files(n).treatment = 'Saline';
files(n).layers = [5 6]; 
files(n).notes = 'poor vis and drift';  %%% noted by cmn 102616, some drift and poor vis resp
files(n).misc = '';
files(n).badsites = [32 26 20 18 17 7 5 4];
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  

n=n+1;
files(n).expt = '100215';
files(n).dir = '10_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_10_02_15_cluster_10_02_15';
files(n).analysisfile = 'analysis_100215';
files(n).predark = 'dark_presal3';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal1';
files(n).predrift = 'drift_presal1';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = 'bars_presal1';
files(n).postbars = 'bars_postsal1';
files(n).prebackground = 'background_presal1';
files(n).postbackground = 'background_postsal1';
files(n).injection = 'injection';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'drift'; %re-selected...still bad unis
files(n).misc = '';
files(n).badsites = [7 ];
files(n).tip1 = 550; files(n).tip2 = 525; files(n).angle = 40;  


n=n+1;
files(n).expt = '093015';
files(n).dir = '09_30_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_30_15_cluster_093015';
files(n).analysisfile = 'analysis_093015b';
files(n).predark = 'dark_predoi4';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drfit_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = []; %[44 40 27 20 19 18 14 13 11 10 7 6];
files(n).tip1 = 475; files(n).tip2 = 475; files(n).angle = 40;  


n=n+1;
files(n).expt = '092915';
files(n).dir = '09_29_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_29_15_cluster_092915';
files(n).analysisfile = 'analysis_092915b';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data' %'drift';--reseleced units
files(n).misc = '';
files(n).predark_camera = '09_29_15_bars_predoi_eye';  
files(n).postdark_camera = '09_29_15_bars_postdoi_eye'; 
files(n).badsites = [];%[4 5];%[26 25 24 22 21 19 18 17 15];
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  


n=n+1;
files(n).expt = '092315';
files(n).dir = '09_23_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_23_15_cluster_092315';
files(n).analysisfile = 'analysis_092315b';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [];
files(n).tip1 = 575; files(n).tip2 = 600; files(n).angle = 50;  


n=n+1;
files(n).expt = '092115';
files(n).dir = '09_21_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_21_15_cluster_092115';
files(n).analysisfile = 'analysis_092115';
files(n).predark = 'dark_presal1';
files(n).postdark = 'dark_postsal1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsal1';
files(n).predrift = 'drift_presal';
files(n).postdrift = 'drift_postsal1';
files(n).prebars = 'bars_presal1';
files(n).postbars = 'bars_postsal1';
files(n).prebackground = 'background_presal1';
files(n).postbackground = 'background_postsal1';
files(n).injection = 'inject_period';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [19 18 16 15];
files(n).tip1 = 525; files(n).tip2 = 550; files(n).angle = 45;  


% n=n+1;
% files(n).expt = '091815';
% files(n).dir = '09_18_15';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_09_18_15_cluster_091815a';
% files(n).analysisfile = 'analysis_091815a';
% files(n).predark = 'dark_presal1';
% files(n).postdark = 'dark_postsal1';
% files(n).prewn = 'wn_presal1';
% files(n).postwn = 'wn_postsal1';
% files(n).predrift = 'drift_presal1';
% files(n).postdrift = 'drift_postsal1';
% files(n).prebars = 'bars_presal1';
% files(n).postbars = 'bars_postsal1';
% files(n).prebackground = 'background_presal1';
% files(n).postbackground = 'background_postsal1';
% files(n).injection = 'injection_period';
% files(n).treatment = 'Saline';
% files(n).layers = [];
% files(n).notes = 'good data'; getSpeed error...not sure why
% files(n).misc = '';

n=n+1;
files(n).expt = '091415';
files(n).dir = '09_14_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_14_15_cluster_09_14_15';
files(n).analysisfile = 'analysis_091415a';
files(n).predark = 'dark_presal1';
files(n).postdark = 'dark_postsaline1';
files(n).prewn = 'wn_presal1';
files(n).postwn = 'wn_postsaline1';
files(n).predrift = '' %'drift_presal1'; %drift post has a break
files(n).postdrift = ''%'drift_postsaline1';
files(n).prebars = 'bars_presal1';
files(n).postbars = 'bars_postsaline1';
files(n).prebackground = 'background_presal1';
files(n).postbackground = 'background_postsaline';
files(n).injection = 'injection_period';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'poor vis and drift'; %%% noted by cmn 102616 - all of one shank seems bad, so unlikely other one is okay
files(n).misc = '';
files(n).badsites = [];%[3 4 5 6 7 8 9 10 11 12 14 16 17 21 26 27 28 30 31 34 36 37 38];
files(n).tip1 = 675; files(n).tip2 = 600; files(n).angle = 45;  


n=n+1;
files(n).expt = '090815';
files(n).dir = '09_08_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_08_15_cluster_090815';
files(n).analysisfile = 'analysis_090815b';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data'; %re-selected
files(n).misc = '';
files(n).badsites = [];
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  


n=n+1;
files(n).expt = '090715';
files(n).dir = '09_07_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_07_15_cluster_090715';
files(n).analysisfile = 'analysis_090715b';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'darkness_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';%re-selected
files(n).misc = '';
files(n).badsites = [];
files(n).tip1 = 675; files(n).tip2 = 600; files(n).angle = 45;  


n=n+1;
files(n).expt = '090415';
files(n).dir = '09_04_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_04_15_cluster_090415';
files(n).analysisfile = 'analysis_090415';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';  %tried to re-select, still lots of bad units
files(n).misc = '';
files(n).badsites = [45 44 43 41 40 39 38];

n=n+1;
files(n).expt = '090215';
files(n).dir = '09_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_09_02_15_cluster_090215';
files(n).analysisfile = 'analysis_090215b';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = 'background_predoi1';
files(n).postbackground = 'background_postdoi1';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).badsites = [];
files(n).tip1 = 700; files(n).tip2 = 700; files(n).angle = 45;  

n=n+1;
files(n).expt = '083115';
files(n).dir = '08_31_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_31_15_cluster_083115';
files(n).analysisfile = 'analysis_083115';
files(n).predark = 'dark_prelis1';
files(n).postdark = 'dark_postlis1';
files(n).prewn = 'wn_prelis1';
files(n).postwn = 'wn_postlis1';
files(n).predrift = 'drift_prelis1';
files(n).postdrift = 'drift_postlis1';
files(n).prebars = 'bars_prelis1';
files(n).postbars = 'bars_postlis1';
files(n).prebackground = 'background_prelis1';
files(n).postbackground = 'background_postlis1';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [];

n=n+1;
files(n).expt = '082615';
files(n).dir = '08_26_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_26_15_cluster_082615';
files(n).analysisfile = 'analysis_082615';
files(n).predark = 'dark_prelis1';
files(n).postdark = 'dark_postlis1';
files(n).prewn = 'wn_prelis1';
files(n).postwn = 'wn_postlis1';
files(n).predrift = 'drift_prelis1';
files(n).postdrift = 'drift_postlis1';
files(n).prebars = 'bars_prelis1';
files(n).postbars = 'bars_postlis1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';

n=n+1;
files(n).expt = '082515';
files(n).dir = '08_25_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_25_15_clust';
files(n).analysisfile = 'analysis_082515';
files(n).predark = 'dark_prelis1';
files(n).postdark = 'dark_poslis1';
files(n).prewn = 'wn_prelis1';
files(n).postwn = 'wn_postlis1';
files(n).predrift = 'drift_prelis1';
files(n).postdrift = 'drift_poslis1';
files(n).prebars = 'bars_prelis1';
files(n).postbars = 'bars_postlis1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';

n=n+1;
files(n).expt = '082115';
files(n).dir = '08_21_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_21_15_cluster_082115';
files(n).analysisfile = 'analysis_082115b';
files(n).predark = 'dark_presaline1'; %quiet...maybe leave out...look at sorting
files(n).postdark = 'dark_postsaline1';
files(n).prewn = 'wn_presaline1';
files(n).postwn = 'wn_postsaline1';
files(n).predrift = 'drift_presaline1';
files(n).postdrift = 'drift_postsaline1';
files(n).prebars = 'bars_presaline1';
files(n).postbars = 'bars_postsaline1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'good data' %'something shifted during first drift. maybe redo from wn on? also clipped units';
files(n).misc = '';
files(n).badsites = []
files(n).tip1 = 650; files(n).tip2 = 625; files(n).angle = 45;  %%% example


n=n+1;
files(n).expt = '081915';
files(n).dir = '08_19_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_19_15_cluster_081815';
files(n).analysisfile = 'analysis_081915';
files(n).predark = 'dark_predoi1';
files(n).postdark = 'dark_postdoi1';
files(n).prewn = 'wn_predoi1';
files(n).postwn = 'wn_postdoi1';
files(n).predrift = 'drift_predoi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_predoi1';
files(n).postbars = 'bars_postdoi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';
files(n).badsites = [ 22 21];

n=n+1;
files(n).expt = '081315';
files(n).dir = '08_13_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_13_15_cluster_081315a';
files(n).analysisfile = 'analysis_081315a';
files(n).predark = 'dark_pre_lisuride1';
files(n).postdark = 'dark_post_lisuride1';
files(n).prewn = 'wn_pre_lisuride1';
files(n).postwn = 'wn_post_lisuride1';
files(n).predrift = 'drift_pre_lisuride1';
files(n).postdrift = 'drift_post_lisuride1';
files(n).prebars = 'bars_pre_lisuride1';
files(n).postbars = 'bars_post_lisuride1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Lisuride';
files(n).layers = [];
files(n).notes = 'drift';
files(n).misc = '';

n=n+1;
files(n).expt = '081215';
files(n).dir = '08_12_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_12_15_cluster_081215';
files(n).analysisfile = 'analysis_081215b';
files(n).predark = 'dark_pre_saline1';
files(n).postdark = 'dark_post_saline1';
files(n).prewn = 'wn_pre_saline1';
files(n).postwn = 'wn_post_saline1';
files(n).predrift = 'drift_pre_saline1';
files(n).postdrift = 'drift_post_saline1';
files(n).prebars = 'bars_pre_saline1';
files(n).postbars = 'bars_post_saline1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'Saline';
files(n).layers = [];
files(n).notes = 'good data';%re-did select-units
files(n).misc = '';
files(n).badsites = [8 14 17 19 23 24]; 
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 40;  %%% example


n=n+1;
files(n).expt = '080715';
files(n).dir = '08_07_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_07_15_cluster_080715';
files(n).analysisfile = 'analysis_080715b';
files(n).predark = 'dark_pre_doi1';
files(n).postdark = 'dark_post_doi1';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_post_doi1';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data'; %re-selected units 
files(n).misc = '';
files(n).badsites = []; % bad sites for a version of afile [29 28 27 25 24 23 22 17 16 6]; %accidentally selected most units from last tetrode before looking at them
files(n).tip1 = 600; files(n).tip2 = 600; files(n).angle = 45;  %%% example


n=n+1;
files(n).expt = '080515';
files(n).dir = '08_05_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_05_15_cluster_080515';
files(n).analysisfile = 'analysis_080515';
files(n).predark = 'dark_pre_doi_2';
files(n).postdark = 'dark_post_doi_2';
files(n).prewn = 'wn_pre_doi_2';
files(n).postwn = 'wn_post_doi_2';
files(n).predrift = 'drift_pre_doi2';
files(n).postdrift = 'drift_post_doi2';
files(n).prebars = 'bars_pre_doi2';
files(n).postbars = 'bars_post_doi2';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period2';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'bad data'; %very noisy
files(n).misc = '';
files(n).badsites = [1 2 3 4 6]

n=n+1;
files(n).expt = '080315';
files(n).dir = '08_03_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_03_15_cluster_080315';
files(n).analysisfile = 'analysis_080315';
files(n).predark = 'dark_pre_doi1';
files(n).postdark = 'dark_post_doi1';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_post_doi2';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift'; %maybe try re-clustering
files(n).misc = '';

n=n+1;
files(n).expt = '080215';
files(n).dir = '08_02_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_08_02_15_cluster_080215';
files(n).analysisfile = 'analysis_080215';
files(n).predark = 'dark_pre_doi2';
files(n).postdark = 'darkness_post_doi1';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_postdoi1';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period2';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'drift';  %re-selected units and most were bad...bad data%%% most cells on shank 1 are badsites, marked by cmn 103116
files(n).misc = '';
%files(n).badsites = [23 22 21 20 15 14 12 10 9 8 7 5 4 3];
files(n).tip1 = 550; files(n).tip2 = 550; files(n).angle = 45;  %%% example


n=n+1;
files(n).expt = '072915';
files(n).dir = '7_29_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_29_15_cluster_072915';
files(n).analysisfile = 'analysis_072915c';
files(n).predark = 'dark_pre_doi1'; %very quiet...maybe leave this block out
files(n).postdark = 'dark_post_injection2';
files(n).prewn = 'wn_pre_doi1';
files(n).postwn = 'wn_post_doi1';
files(n).predrift = 'drift_pre_doi1';
files(n).postdrift = 'drift_post_doi1';
files(n).prebars = 'bars_pre_doi1';
files(n).postbars = 'bars_post_doi1';
files(n).prebackground = '';
files(n).postbackground = '';
files(n).injection = 'injection_period';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data' % re-selected units %'drift';  %%% most sites on shank 1 showed drift, marked by cmn 103116
files(n).misc = '';
files(n).badsites = [];
files(n).tip1 = 450; files(n).tip2 = 450; files(n).angle = 45; 


n=n+1;
files(n).expt = '072515';
files(n).dir = '7_25_15';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_25_15_cluster_data';
files(n).analysisfile = 'analysis_file';
files(n).predark = 'dark_pre_doi_rec1';
files(n).postdark = 'dark_post_doi_7 min';
files(n).prewn = 'wn_pre_doi_rec1';
files(n).postwn = 'wn_post_doi_rec1';
files(n).predrift = 'drift_pre_doi_rec1';
files(n).postdrift = 'drift_post_doi_rec1';
files(n).prebars = 'bars_pre_doi_rec1';
files(n).postbars = 'bars_post_doi_rec1';
files(n).injection = 'injectionperiod';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'poor vis resp';   %%% marked by cmn 103116
files(n).misc = '';
files(n).badsites = [7 6 5 1];

n=n+1;
files(n).expt = '072315';
files(n).dir = '7_23_15_recluster';
files(n).tank = '';
files(n).clusterfile = 'cluster_data_07_23_15_cluster_data';
files(n).analysisfile = 'analysis_07_23_15b';
files(n).predark = 'dark_predoi_rec1';
files(n).postdark = 'dark_post_doi_rec2';
files(n).prewn = 'wnmovie_pre_doi_rec1';
files(n).postwn = 'wnmovie_post_doi_rec1';
files(n).predrift = 'drift_pre_doi_rec1';
files(n).postdrift = 'drift_post_doi_rec1';
files(n).prebars = 'bars_pre_doi_rec1';
files(n).postbars = 'bars_post_doi_rec1';
files(n).injection = '';
files(n).treatment = 'DOI';
files(n).layers = [];
files(n).notes = 'good data';
files(n).misc = '';
files(n).tip1 = 500; files(n).tip2 = 500; files(n).angle = 45; %need to check

% n=n+1;
% files(n).expt = '7_16_15';
% files(n).dir = '7_16_15';
% files(n).tank = '';
% files(n).clusterfile = 'cluster_data_07_16_15_07_16_15_etohcontrol_cluster_data';
% files(n).analysisfile = 'analysis_etoh_control';
% files(n).predark = 'dark_before_rec1';
% files(n).postdark = 'dark_post_injection_rec2_7min';
% files(n).prewn = 'wnmovie_before_rec1';
% files(n).postwn = 'wnmovie_post_injection_rec1';
% files(n).predrift = 'drift_before_rec1';
% files(n).postdrift = 'drift_post_injection_rec1';
% files(n).prebars = 'bars_baseline_rec1';
% files(n).postbars = 'bars_post_injection_rec2';
% files(n).injection = '';
% files(n).treatment = 'EtOH';
% files(n).layers = [];
% files(n).notes = 'good data';



for f = 1:length(files);
    files(f).blockWn = {files(f).prewn files(f).postwn};
    files(f).blockDark = {files(f).predark files(f).postdark};
    files(f).blockBar = {files(f).prebars files(f).postbars};
    files(f).blockDrift = {files(f).predrift files(f).postdrift};
end


