function Hd = notch_filter
%NOTCH_FILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.13 and the DSP System Toolbox 8.1.
%
% Generated on: 14-Oct-2013 13:52:52
%

N     = 6;       % Order
F0    = 60;      % Center frequency
BW    = 6;       % Bandwidth
Astop = 100;     % Stopband Attenuation (dB)
Fs    = 762.94;  % Sampling Frequency

h = fdesign.notch('N,F0,BW,Ast', N, F0, BW, Astop, Fs, 'Squared');

Hd = design(h, 'cheby2', ...
    'SOSScaleNorm', 'Linf');

set(Hd, 'Arithmetic', 'double');

% [EOF]
